web/console/.eslintignore
web/console/package.json
web/console/tsconfig.json
web/installer/tsconfig.json

remove config in tsconfig、package.json that about tea-cli

feat: remove tea-cli config

---

README.md
docs/devel/development.md

Add Requirement：Git-LFS 

---

pkg/platform/registry/cluster/storage/csioperator.go
pkg/platform/registry/cluster/storage/pvcr.go

fix storage group name path. Related to #6 #7

update storage group name

---

pkg/platform/controller/addon/lbcf/controller.go
pkg/platform/controller/addon/lbcf/images/images.go
pkg/platform/registry/cluster/storage/lbcf_backendgroup.go
pkg/platform/registry/cluster/storage/lbcf_backendrecord.go
pkg/platform/registry/cluster/storage/lbcf_driver.go
pkg/platform/registry/cluster/storage/lbcf_loadbalancer.go

api group of lbcf modified to lbcf.tkestack.io

---

pkg/platform/registry/cluster/storage/tappcontroller.go

Update tapp group name to apps.tkestack.io

Update tapp group name

---

pkg/platform/registry/cluster/storage/cronhpa.go

Update cronhpa group name to extensions.tkestack.io

Update cronhpa group name

---

pkg/util/apiclient/idempotency.go
pkg/util/apiclient/install.go

add `CreateOrUpdateJob` & `CreateOrUpdateCronJob` methods

feat: add job/cronjob resource for apiclient

---

web/console/Wrapper.tsx
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/console/src/modules/cluster/components/clusterManage/SelectICComputerPanel.tsx

fix: issus #77 #76 #71

---

web/console/src/modules/registry/WebAPI.ts
web/console/src/modules/registry/constants/Config.ts
web/console/src/modules/registry/reducers/RootReducer.ts

remove the "https://" prefix of registry url and disable previous localstorage about it

---

build/lib/golang.mk
cmd/README.md
docs/devel/running-locally.md

- Update documentation to run TKE locally.
- Add cmd/README.md to describe TKE components.

docs: update running locally guide

---

docs/devel/running-locally.md

- Fix typo
- Fix  tke-notify-controller configuration guide

fix: Update tke-notify-controller running locally guide

---

pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/yamls.go

fix: typo in prometheus controller

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/rook/operator.yaml

fix an error in influxdb install

Disable fs and flex in rook operator

---

docs/devel/running-locally.md

fix: auth-api and auth-controller json config

---

cmd/tke-installer/app/installer/installer.go
docs/devel/running-locally.md
pkg/platform/util/client.go
pkg/platform/util/location.go
pkg/util/kubeconfig/kubeconfig.go
pkg/util/ssh/ssh.go
web/console/Wrapper.tsx
web/console/config/resource/k8sConfig/otherResource.ts
web/console/helpers/urlUtil.ts
web/console/src/modules/logStash/actions/clusterActions.ts
web/console/src/modules/logStash/actions/logDaemonsetActions.ts
web/console/src/modules/logStash/components/LogStashActionPanel.tsx
web/console/src/modules/logStash/constants/Config.ts
web/console/src/modules/logStash/models/LogStatsh.ts
web/console/src/modules/logStash/models/RootState.ts
web/console/src/modules/logStash/reducers/RootReducer.ts

1. fix the requestPath of logcollector
2. modify the resourceVersion of logcollector

feat: support logcollector and modify resourceVersion for that

---

cmd/tke-installer/app/installer/manifests/tke-notify-controller/tke-notify-controller.yaml
pkg/notify/apiserver/handler.go

Fix bugs in notify

---

Makefile
build/lib/common.mk
build/lib/golang.mk
build/lib/image.mk
docs/devel/development.md

1. Update make help
2. Update golang.mk & image.mk
3. Update doc

feat: build arm64 images via make image PLATFORM=linux_arm64

---

build/docker/tke-notify-api/Dockerfile
pkg/notify/apiserver/handler.go

feat: add summary variable for alarms
fix: use localtime instead of utc in alarms

fix starttime of alarm and add summary variable

---

Makefile
build/lib/create-manifest.sh
build/lib/image.mk
docs/devel/development.md

1. Update image.mk to add hints
2. Update Makefile to support make manifest & manifest.multiarch

Fix: add hints to help users enable docker experimental features

---

build/docker/tke-notify-api/Dockerfile
pkg/notify/apiserver/handler.go

fix: revert setting local timezone for alarms

---

pkg/platform/controller/addon/prometheus/yamls.go

fix: failed to get metrics from cadvisor of k8s v1.12

---

pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/images/images.go

prometheus fix

---

pkg/platform/registry/cluster/strategy.go

fix cluster status update validation

---

pkg/business/controller/chartgroup/chartgroup_health.go
pkg/business/controller/imagenamespace/imagenamespace_health.go
pkg/platform/controller/addon/cronhpa/controller.go
pkg/platform/controller/addon/gpumanager/controller.go
pkg/platform/controller/addon/gpumanager/health/health.go
pkg/platform/controller/addon/gpumanager/health/types.go
pkg/platform/controller/addon/ipam/ipam_checking.go
pkg/platform/controller/addon/ipam/ipam_controller.go
pkg/platform/controller/addon/ipam/ipam_health.go
pkg/platform/controller/addon/lbcf/controller.go
pkg/platform/controller/addon/logcollector/controller.go
pkg/platform/controller/addon/persistentevent/persistentevent_checking.go
pkg/platform/controller/addon/persistentevent/persistentevent_controller.go
pkg/platform/controller/addon/persistentevent/persistentevent_health.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/storage/csioperator/controller.go
pkg/platform/controller/addon/storage/volumedecorator/controller.go
pkg/platform/controller/addon/tappcontroller/controller.go
pkg/platform/controller/cluster/cluster_health.go

fix health and checking key

---

cmd/tke-installer/app/installer/installer.go

add skipSteps in installer

---

pkg/monitor/storage/thanos/metric/metric.go
pkg/platform/controller/addon/prometheus/controller.go

feat: set retention time to 2h to reduce memory usage of prometheus

fix: get metrics failed if values contain NaN

---

pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/machine/provider.go

fix: install gpu driver for machine

---

pkg/platform/controller/addon/ipam/ipam_controller.go

fix: ipam check health

---

build/docker/tools/provider-res/Dockerfile
build/docker/tools/provider-res/download.sh

1. fix: Rename nvidia-container-runtime to end with .tar.gz
2. fix: Update Dockerfile of provider-res to make sure all files are end with .tar.gz

fix: Make sure all files in provider-res are end with tar.gz

---

cmd/tke-notify-api/app/config/config.go
cmd/tke-notify-api/app/options/feature.go
cmd/tke-notify-api/app/options/options.go
cmd/tke-notify-api/app/server.go
pkg/notify/apiserver/apiserver.go
pkg/notify/registry/message/storage/storage.go
pkg/notify/registry/messagerequest/storage/storage.go
pkg/notify/registry/rest/rest.go

Specify ttl of messages and messageRequests; Default value is 30 days

feat: Add option message_ttl to tke-notify-api

---

pkg/platform/proxy/core/service/storage/event.go

Fix the problem of querying the event list of the service when the selector of the service is empty

fix: illegal request to query service event list

---

pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/yamls.go

Add master toleration for alertmanager;
Label project_name of ns should begin with tkestack.io, and add label namespace_name to namespace related metrics.

Prometheus bug fix

---

pkg/platform/provider/imported/cluster/provider.go
pkg/util/validation/validation.go

replace tcp by http request for using http_proxy

replace tcp by http request for using http_proxy

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/machine/create.go

fix: chmod with hook's path

---

build/lib/image.mk

fix: make compatible in macOS

---

pkg/monitor/storage/project/metrics.go
pkg/monitor/storage/project/project.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/yamls.go

feat: Send metrics kube_node_labels and kube_namespace_labels to remote
feat: Add metrics for namespace capacity and allocated

Prometheus feature

---

pkg/monitor/storage/project/metrics.go
pkg/monitor/storage/project/project.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/yamls.go

feat: add more etcd metrics to prometheus config

---

cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/installer.go

fix(tke-installer): validate cpu and memory requirements

---

pkg/platform/provider/baremetal/cluster/create.go

fix: mark master

---

pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/images/images.go
pkg/platform/controller/addon/prometheus/yamls.go

apiserver_request_duration_seconds

fix: replace deprecated metric

---

web/console/.prettierrc
web/console/src/modules/cluster/actions/validateWorkloadActions.ts
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx

fix: close annotation value validator

fix: close annotation value validator

---

web/console/src/modules/alarmPolicy/WebAPI.ts
web/console/src/modules/alarmPolicy/actions/clusterActions.ts
web/console/src/modules/alarmPolicy/components/EditAlarmPolicyObject.tsx
web/console/src/modules/alarmPolicy/constants/ActionType.ts
web/console/src/modules/alarmPolicy/models/Addon.ts
web/console/src/modules/alarmPolicy/models/RootState.ts
web/console/src/modules/alarmPolicy/models/index.ts
web/console/src/modules/alarmPolicy/reducers/RootReducer.ts

feat: alarmplicy support tapp

---

web/console/src/modules/alarmPolicy/actions/projectNamespaceActions.project.ts
web/console/src/modules/alarmPolicy/components/EditAlarmPolicyObject.tsx
web/console/src/modules/alarmPolicy/reducers/RootReducer.project.ts

fix: bussiness alarmPolicy crash

fix: bussiness alarmPolicy crash

---

pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/yamls.go

feat: add new apiserver metrics

---

web/console/src/modules/addon/actions/clusterActions.ts
web/console/src/modules/alarmPolicy/WebAPI.ts
web/console/src/modules/alarmPolicy/components/EditAlarmPolicyObject.tsx
web/console/src/modules/alarmPolicy/components/EditAlarmPolicyPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/EditSecretPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx
web/console/src/modules/cluster/models/MonitorPanel.tsx
web/console/src/modules/project/actions/projectActions.ts
web/console/tsconfig.json

feat: fix monitor ns prefix

---

cmd/tke-upgrade/README.md
cmd/tke-upgrade/app/data/oidc_client_secret
cmd/tke-upgrade/app/data/tke.json
cmd/tke-upgrade/app/options/options.go
cmd/tke-upgrade/main.go
cmd/tke-upgrade/upgrate.sh

add tkestack components upgrade script

feat(tke-upgrate): add tkestack components upgrade script

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-audit-api/tke-audit-api.yaml
cmd/tke-installer/app/installer/types/types.go
pkg/audit/storage/es/es.go

feat: support es basic auth

---

cmd/tke-auth-api/app/config/config.go
cmd/tke-auth-api/app/options/options.go
cmd/tke-business-api/app/config/config.go
cmd/tke-business-api/app/options/options.go
cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml
cmd/tke-installer/app/installer/manifests/tke-business-api/tke-business-api.yaml
cmd/tke-installer/app/installer/manifests/tke-logagent-api/tke-logagent-api.yaml
cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
cmd/tke-installer/app/installer/manifests/tke-notify-api/tke-notify-api.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
cmd/tke-logagent-api/app/config/config.go
cmd/tke-logagent-api/app/options/options.go
cmd/tke-monitor-api/app/config/config.go
cmd/tke-monitor-api/app/options/options.go
cmd/tke-notify-api/app/config/config.go
cmd/tke-notify-api/app/options/options.go
cmd/tke-platform-api/app/config/config.go
cmd/tke-registry-api/app/config/config.go
cmd/tke-registry-api/app/options/options.go
pkg/apiserver/util/audit.go

feat: enable audit in most tke components

---

web/console/Wrapper.tsx
web/console/src/modules/audit/components/AuditPanel.tsx

Audit prob fix

---

api/platform/validation/cluster.go

fix: cluster gpu type validation

---

pkg/platform/registry/cluster/storage/cronhpa.go
pkg/platform/registry/cluster/storage/csioperator.go
pkg/platform/registry/cluster/storage/helm.go
pkg/platform/registry/cluster/storage/lbcf_backendgroup.go
pkg/platform/registry/cluster/storage/lbcf_backendrecord.go
pkg/platform/registry/cluster/storage/lbcf_driver.go
pkg/platform/registry/cluster/storage/lbcf_loadbalancer.go
pkg/platform/registry/cluster/storage/logcollector.go
pkg/platform/registry/cluster/storage/pvcr.go
pkg/platform/registry/cluster/storage/tappcontroller.go

fix(cluster): addon RESTs overwrite apiserver path when sending request

fix(cluster): addon RESTs overwrite apiserver path when sending request

---

web/console/src/modules/cluster/actions/validateSecretActinos.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceDetailPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceModifyHistoryPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNamespaceDetailPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceRollbackDialog.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceYamlPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/UpdateWorkloadPodNumPanel.tsx

1. fix the rollback api for deployment
2. remove the limit of the password in secret
3. fix the page crash when search for specific pod in pod page
4. fix issue #317
close #317

hotfix: fix some problem in console

---

pkg/platform/controller/addon/ipam/images/images.go
pkg/platform/provider/baremetal/phases/galaxy/images/images.go

FYI https://github.com/tkestack/galaxy/pull/73

fix: bump galaxy/ipam version to fix host port issue

---

pkg/platform/util/location.go

fix(cluster): url path in requests sent by addon RESTs should be cut

fix(cluster): url path in requests sent by addon RESTs should be cut

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/cluster/provider.go

- feat(cluster): change kube-proxy default mode to iptables
- fix(cluster): missing clusterCIDR in kube-proxy config

kube proxy

---

pkg/platform/controller/addon/gpumanager/controller.go
pkg/platform/controller/addon/ipam/ipam_controller.go
pkg/platform/controller/addon/tappcontroller/controller.go
pkg/platform/controller/cluster/deletion/cluster_deleter.go

fix(cluster): delete addons when delete cluster

---

cmd/tke-installer/app/installer/installer.go

fix(installer): allow to set version

---

pkg/platform/types/types.go
pkg/platform/types/v1/types.go

fix(cluster): get credential not in clusterCredentialRef

---

pkg/platform/controller/addon/storage/volumedecorator/images/images.go

update the volume-decorator image with a tag of v1.0.1

fix(platform): failed installation of VolumeDecorator

---

web/console/src/modules/cluster/actions/validateWorkloadActions.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceGrayUpgradeDialog.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodRemoteLoginDialog.tsx
web/console/src/modules/cluster/constants/Config.ts

1. support to select shell type for container login
2. modify the regexp for the env of container
3. add the warning info for the gray update for tapp

feat: support to select shell type for container login，fix the regexp of the env of container

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml

fix(installer): add gpu-manager cm

---

pkg/platform/provider/imported/cluster/delete.go
pkg/platform/provider/imported/cluster/provider.go
pkg/platform/provider/imported/util/mark/mark.go

fix(cluster): clean cluster mask when deleting imported cluster

---

pkg/notify/registry/receiver/strategy.go
pkg/notify/registry/receivergroup/strategy.go

fix(notify): allow user-define name for recv and recvgrp

---

pkg/platform/controller/addon/prometheus/controller.go

feat(platform): add tenantID and clusterDisplayName to external

---

pkg/platform/provider/baremetal/images/images.go
pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml

Signed-off-by: mYmNeo <thomassong2012@gmail.com>

fix: Upgrade gpu-manager version to v1.0.4

---

cmd/generate-images/main.go

galaxy-ipam support multiarch

---

build/docker/tools/tke-installer/install.sh

Value of i should be 60 if docker fails to startup.

fix: docker startup err not detected

---

pkg/platform/controller/addon/ipam/ipam_controller.go

install galaxy-ipam的时候需要创建floatingip-config

fix: create floatingIP configmap

---

pkg/platform/controller/addon/gpumanager/template/template.go

fix(cluster): gpu-manager remove read-only on /var/run

---

pkg/platform/controller/addon/prometheus/yamls.go

fix(platform): do not sum node filesystem metric

---

pkg/platform/controller/addon/prometheus/yamls.go

fix(platform): fix syntax error for node filesystem metrics

---

web/console/lib/ff-component/src/tablepanel/TablePanel.tsx
web/console/src/modules/cluster/actions/namespaceActions.project.ts
web/console/src/modules/cluster/actions/namespaceActions.ts
web/console/src/modules/cluster/actions/resourceActions.ts
web/console/src/modules/cluster/actions/resourceDetailActions.ts
web/console/src/modules/cluster/actions/resourceRsActions.ts
web/console/src/modules/cluster/actions/validateWorkloadActions.ts
web/console/src/modules/cluster/actions/workflowActions.ts
web/console/src/modules/cluster/actions/workloadEditActions.ts
web/console/src/modules/cluster/components/ApplicationApp.project.tsx
web/console/src/modules/cluster/components/resource/ResourceContainerPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceDetail.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceDetailPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceModifyHistoryPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNamespaceDetailPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNodeDetailPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceYamlPanel.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerEnvItem.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceTablePanel.tsx
web/console/src/modules/cluster/constants/Config.ts
web/console/src/modules/cluster/constants/initState.ts
web/console/src/modules/cluster/models/ContainerEnv.ts
web/console/src/modules/cluster/models/ContainerItem.ts
web/console/src/modules/cluster/models/ResourceDetailState.ts
web/console/src/modules/cluster/models/index.ts
web/console/src/modules/cluster/reducers/ResourceDetailReducer.ts

suppor the valueFrom of env in container like fieldRef, resourceFieldRef, etc...

feat: support the fieldRef of env in container

---

pkg/platform/provider/baremetal/res/res.go

fix(cluster): kubernetes node versions

---

pkg/platform/provider/baremetal/res/res.go

fix(cluster): kubeadm versions

---

pkg/notify/apiserver/handler.go

feat(notify): add clusterDisplayName to alarm variables

---

web/console/src/modules/cluster/actions/resourceActions.project.ts

fix: bussiness lbcf can find backgroup

fix: bussiness lbcf can find backgroup

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml

fix(cluster): set svc gpu-quota-admission clusterIP

---

pkg/platform/controller/addon/ipam/ipam_controller.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/manifests.go
pkg/platform/provider/baremetal/constants/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(cluster): allocate galaxy ipam service ip

---

cmd/tke-installer/app/installer/installer.go

/kind bug
params in yaml of tke-monitor-controller added by commit b8a7cefa44cbbb8e2cfd1e7a5ad9592193a58f70 should be set
Fixes #
```release-note
NONE
```
```docs
```

fix(installer): set value of new params for tke-monitor-controller

---

pkg/gateway/api/sysinfo.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(logagent): add logagent in sysinfo

---

web/console/package-lock.json
web/console/src/modules/alarmPolicy/WebAPI.ts
web/console/src/modules/alarmPolicy/actions/alarmPolicyActions.ts
web/console/src/modules/alarmPolicy/actions/clusterActions.ts
web/console/src/modules/alarmPolicy/components/AlarmPolicyTablePanel.tsx
web/console/src/modules/alarmPolicy/models/AlarmPolicy.ts
web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/resourceActions.project.ts
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceTablePanel.tsx
web/console/src/modules/project/components/NamespaceTablePanel.tsx
web/console/src/modules/project/components/ProjectActionPanel.tsx
web/installer/src/modules/installer/WebAPI.ts

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix bussiness resource not found

---

pkg/platform/controller/addon/tappcontroller/images/images.go

/kind feature
Fixes #
```release-note
NONE
```
```docs
```

feat(platform): bump up tapp controller version to v1.1.0

---

pkg/audit/storage/es/es.go

>
/kind bug
> /kind design
> /kind flake
1. password stored in configmap is base64 encoded, decode when use it
2. support es v7
Fixes #
```release-note
```
```docs
```

fix(audit): es password decode and es v7 support

---

pkg/monitor/controller/prometheus/controller.go
pkg/monitor/controller/prometheus/metrics.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/metrics.go

add label prometheus_name to metric prometheus_status_fail.
delete series of metric prometheus_status_fail if prometheus was deleted.
Fixes #
```release-note
NONE
```
```docs
```

Prometheus update

---

pkg/util/ssh/ssh.go

/kind improvement
Optimize ssh memory by temp file.
Fixes #
```release-note
```
```docs
```

refactor: optimize ssh memory

---

go.mod
go.sum

…ew address
>
> /kind bug
> /kind design
> /kind flake
Fixes #551 
```release-note
```
```docs
```

fix(go.mod): replace domain-role-manager with a new address

---

cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): modify tke-monitor-api configuration

---

pkg/monitor/controller/prometheus/yamls.go
pkg/platform/controller/addon/prometheus/yamls.go

Add more metrics scraped by prometheus 
Fixes #
```release-note
NONE
```
```docs
```

feat(prometheus): add more metrics scraped by prometheus

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/installer_test.go
pkg/util/validation/validation.go

This PR improves validation logic of tke-installer to support wildcard certificates

support wildcard cert

---

cmd/tke-installer/app/installer/installer.go

> /kind bug
Fixes #
```release-note
```
```docs
```

fix(audit): enable global components audit

---

go.mod
pkg/auth/controller/policy/policy_controller.go
pkg/auth/util/role_manager.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(auth): adapt platform policies and business policies

---

pkg/platform/controller/addon/lbcf/controller.go

/kind bug
LBCF health check is not handling `Failed` phase correctly. Once failed, it stops checking and leaves the lbcf addon in `Failed` phase.
```release-note
NONE
```

fix(addon): LBCF health check keeps running if fail

---

pkg/platform/controller/addon/tappcontroller/controller.go

/kind bug
Cherry-pick from https://github.com/tkestack/tke/pull/588
Once TAPP addon is in failed state, TAPP addon controller stops checking and leaves the TAPP addon in Failed phase. Howerver it might become running, so we need to do health check for this state.
Fixes #
```release-note
NONE
```
```docs
```

fix(addon): keep checking health when TAPP addon is in failed state

---

api/platform/cluster.go
api/platform/v1/cluster.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/config/config.go
pkg/platform/proxy/client.go

feat(cluster): auto add authz webhook when open audit

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/util/apiclient/idempotency.go
pkg/util/apiclient/install.go

> /kind bug
support creating apiservice
Fixes #
```release-note
NONE
```
```docs
```

fix(platform): support create APIService in apiclient

---

cmd/tke-installer/app/installer/installer.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/config/config.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(cluster): add authz webhook if business enabled

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml

> /kind bug
add metrics-server configmapt to tke-platform
Fixes #
```release-note
```
```docs
```

fix(installer): add metrics-server configmap

---

hack/auth/policy.json

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

build(policy.json): add listuserprojects permission to project roles

---

pkg/gateway/assets/assets.go
pkg/gateway/gateway.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(gateway): asset routing supports header request

---

docs/devel/components.md
docs/devel/running-locally.md

Signed-off-by: huxiaoliang vvictorhu@tencent.com
> /kind bug
Fixes #
```release-note
```
```docs
```

fix: dead link

---

api/platform/v1/cluster.go
cmd/tke-installer/app/installer/installer.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/config/config.go
pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go
web/console/src/modules/project/components/NamespaceTablePanel.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(cluster): support-authZ-4-global-cluster

---

pkg/auth/util/group.go
pkg/auth/util/user.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): adapt the domain name for platform policies

---

pkg/platform/types/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(cluster): query credentials and be compatible with older clusters

---

pkg/auth/registry/localidentity/validation.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): change users' own password

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add retry logic for installer check

---

web/console/src/modules/cluster/components/resource/resourceEdition/EditServiceWorkloadDialog.tsx
web/console/src/modules/cluster/constants/Config.ts

>
Fixes #
```release-note
```
```docs
```

feat: support selector of daemon & tapp when creating service

---

pkg/monitor/controller/prometheus/yamls.go
pkg/platform/controller/addon/prometheus/yamls.go

add more prometheus metrics 
Fixes #
```release-note
```
```docs
```

feat(prometheus): update prometheus metrics

---

web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
web/console/src/modules/cluster/actions/projectNamespaceActions.project.ts
web/console/src/modules/uam/components/strategy/StrategyActionPanel.tsx

kind bug
bugfix
Fixes #
fix: the description of the strategy is incomplete
fix: business manage pod remove problem
fix: business manage, business & namespace switch linkage problem
```release-note
```
```docs
```

Ams problems fix

---

web/console/Wrapper.tsx
web/console/helpers/urlUtil.ts
web/console/src/modules/common/models/Namespace.ts
web/console/src/modules/logStash/actions/clusterActions.ts
web/console/src/modules/logStash/actions/editLogStashActions.ts
web/console/src/modules/logStash/actions/namespaceActions.ts
web/console/src/modules/logStash/actions/workflowActions.ts
web/console/src/modules/logStash/components/EditLogStashPanel.tsx
web/console/src/modules/logStash/components/EditOriginContainerFilePanel.tsx
web/console/src/modules/logStash/components/EditOriginContainerItemPanel.tsx
web/console/src/modules/logStash/components/EditOriginContainerPanel.tsx
web/console/src/modules/logStash/components/ListOriginContainerItemPanel.tsx
web/console/src/modules/logStash/components/LogDetailPanel.tsx
web/console/src/modules/logStash/components/LogStashActionPanel.tsx
web/console/src/modules/logStash/components/LogStashTablePanel.tsx

- refactoring status checking for cluster and add-on
- bug fix related to namespace on business side
- constraints on changing namespace while editing an existed collection rule

fix(console): logstash v3 updated

---

docs/design-proposals/api-trunking-combination-query-support.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(docs): fix dead link

---

pkg/monitor/util/cache/cache.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(monitor): solve the problem of checking multiple etcd components

---

web/console/src/modules/logStash/WebAPI.ts

fetchNamespaceList for logStash updated

fix(console): namespace list for logstash updated

---

cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml

fix #579
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): increase-resource

---

docs/design-proposals/api-trunking-combination-query-support.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(common): api trunking and combination query refine

---

api/monitor/types.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
cmd/tke-monitor-api/app/config/config.go
cmd/tke-monitor-api/app/options/options.go
pkg/monitor/registry/overview/cluster/storage/storage.go
pkg/monitor/util/cache/cache.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(monitor): decouple monitor and business

---

pkg/gateway/webtty/handler.go
pkg/gateway/webtty/stream.go
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodRemoteLoginDialog.tsx

>
> /kind bug
add project header when use webtty in project view

fix(gateway): webtty add project header

---

pkg/monitor/controller/prometheus/controller.go
pkg/platform/controller/addon/prometheus/controller.go

add more info to logs of prometheus install
Fixes #
```release-note
```
```docs
```

feat(prometheus): add more info to logs of prometheus install

---

pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): enable-nvidia-device

---

pkg/auth/registry/project/storage/group.go
pkg/auth/registry/project/storage/user.go
pkg/auth/registry/user/storage/project.go
pkg/logagent/controller/logagent/logagent_controller.go
pkg/monitor/controller/prometheus/yamls.go
pkg/platform/controller/addon/helm/helm_prober.go
pkg/platform/controller/addon/logcollector/controller.go
pkg/platform/controller/addon/prometheus/yamls.go
pkg/platform/provider/baremetal/phases/image/image.go
pkg/platform/provider/baremetal/phases/kubelet/kubelet.go

/kind bug
Remove unnecessary code.
Fixes #666
```release-note
```
```docs
```

fix(lint): make lint error

---

web/console/Wrapper.tsx
web/installer/src/modules/installer/actions/validateActions.ts
web/installer/src/modules/installer/components/Step3.tsx
web/installer/src/modules/installer/components/Step6.tsx
web/installer/src/modules/installer/components/Step9.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat: installer fix bug

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/util/apiclient/install.go

some features to supports eks

---

web/console/Wrapper.tsx
web/console/src/modules/alarmPolicy/actions/namespaceActions.project.ts
web/console/src/modules/alarmPolicy/components/AlarmPolicyHeadPanel.project.tsx
web/console/src/modules/alarmPolicy/models/Namespace.ts
web/console/src/modules/cluster/actions/namespaceActions.project.ts
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceEventPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceLogPanel.tsx
web/console/src/modules/cluster/models/Namespace.ts
web/console/src/modules/helm/actions/namespaceActions.project.ts
web/console/src/modules/helm/components/helmManage/list/HelmHeadPanel.project.tsx
web/console/src/modules/helm/models/Namespace.ts
web/console/tsconfig.json
web/console/webpack/webpack.dev.js
web/console/webpack/webpack.prod.js

/kind feature
Fixes #
```release-note
```
```docs
```

feat(console): project console namespace select support groups

---

web/console/Wrapper.tsx
web/console/src/modules/cluster/actions/validateWorkloadActions.ts
web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx
web/console/src/modules/overview/components/OverviewHeadPanel.tsx
web/console/src/modules/project/components/SelectExistProjectDialog.tsx

/kind bug
Fixes #
1、新建workload时label key支持‘/’；
2、集群列表中id过长时不显示复制按钮的问题
3、页面显示多余的“；”和不正确的竖线
4、页面指引地址以及位置变更
```release-note
```
```docs
```

fix(console): 修复页面显示中的一些问题

---

web/console/helpers/downloadCrt.ts
web/console/helpers/index.ts
web/console/package-lock.json
web/console/package.json
web/console/src/modules/cluster/components/KubectlDialog.tsx

/kind feature
need copy or download kebeconfig and kubectl guide
Fixes #
```release-note
```
```docs
```

feat(console): add kubeconfig and guide

---

web/console/src/modules/cluster/actions/createICAction.ts
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/console/src/modules/cluster/reducers/CreateICReducer.ts

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console):  修复创建集群时k8s版本未选择也能创建的bug

---

web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/createICAction.ts
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/console/src/modules/cluster/constants/ActionType.ts
web/console/src/modules/cluster/models/CreateIC.ts
web/console/src/modules/cluster/reducers/CreateICReducer.ts
web/installer/src/modules/installer/WebAPI.ts

>
we need support on install page mertice serever default is enable, on console create cluster mertice serever is can enable
Fixes #
```release-note
```
```docs
```
https://github.com/tkestack/tke/pull/692

feat(console): support enable metrics server

---

api/platform/types.go
api/platform/v1/types.go
api/platform/validation/cluster.go
docs/user/cluster/hooks.md
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/cluster/update.go
pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/machine/provider.go
pkg/platform/provider/baremetal/machine/update.go
pkg/platform/provider/baremetal/util/util.go
pkg/util/ssh/ssh.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): add more customized hooks

---

docs/user/tke-installer/normal-installation.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs(installer): update installer guide

---

web/installer/src/modules/installer/WebAPI.ts

>
> /kind bug
Before call the create cluster api, flat the host as multiple hosts
https://github.com/tkestack/tke/issues/659
Fixes #
```release-note
```
```docs
```

fix(install): fix HA config for master host list failed on UI validation

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/machine/provider.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): adjust EnsureDisableOffloading order

---

web/installer/src/modules/installer/WebAPI.ts
web/installer/src/modules/installer/components/Step5.tsx
web/installer/src/modules/installer/models/RootState.ts
web/installer/src/modules/installer/reducers/initState.ts

>
Fixes #
```release-note
```
```docs
```
https://github.com/tkestack/tke/pull/706

feat(install): support enable application

---

web/console/src/modules/application/WebAPI.ts
web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
web/console/src/modules/project/UserManageWebAPI.ts
web/console/src/modules/registry/WebAPI.ts

>
> /kind bug
1. fix project pod rollback fail
2.add http header “X-TKE-ProjectName: ” on project api request
Fixes #
```release-note
```
```docs
```

fix(console): fix some api request error

---

web/installer/webpack/webpack.prod.js

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): fix CI can't pick up installer web commit

---

hack/auth/policy.json

Revert "build(policy.json): add action of createpodexec to viewer"

---

pkg/notify/apiserver/handler.go

> /kind bug
make alarm variable summary more readable by adding "\n" and descriptions
Fixes #
```release-note
```
```docs
```

fix(notify): make value summary more readable

---

cmd/tke-installer/app/installer/installer.go

Please cherry pick to release-1.3
/kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): miss sysctl.conf

---

pkg/util/apiclient/idempotency.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): update cm from file

---

pkg/auth/util/adapter.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): fix invalid number of tokens when empty strings appear

---

pkg/util/apiclient/idempotency.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): apply configmap ignore resourceVersion

---

web/installer/src/modules/installer/WebAPI.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(install): fix gputype overwrite enableMetricsServer

---

web/installer/src/modules/installer/actions/validateActions.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(install): allowed es username and passworld empty

---

pkg/platform/proxy/extensions/ingress/storage/event.go

fix(cluster): ingress apigroup replacement problem

---

pkg/platform/controller/addon/ipam/images/images.go
pkg/platform/provider/baremetal/phases/galaxy/images/images.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
galaxy change log https://github.com/tkestack/galaxy/blob/master/CHANGELOG.md
Fixes #
```release-note
update galaxy version, changelog https://github.com/tkestack/galaxy/blob/master/CHANGELOG.md
```
```docs
```

fix(galaxy): update galaxy version

---

pkg/platform/controller/addon/tappcontroller/images/images.go

/kind feature
Bump up tapp controller version to v1.1.1
Fixes #
```release-note
NONE
```
```docs
```

feat(platform): bump up tapp controller version to v1.1.1

---

web/console/src/modules/addon/actions/addonActions.ts
web/console/src/modules/addon/components/EditAddonPanel.tsx
web/console/src/modules/alarmPolicy/components/AlarmPolicyTablePanel.tsx
web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/clusterActions.ts
web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx
web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterDetail.tsx
web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterDetailBasicInfoPanel.tsx
web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterPlugInfoPanel.tsx
web/console/src/modules/common/models/Cluster.ts
web/console/src/modules/common/webapi/K8sResourceAPI.ts
web/console/src/modules/common/webapi/PromethusAPI.ts
web/console/src/modules/common/webapi/index.ts
web/console/src/modules/uam/actions/userActions.ts

>
1、可以在集群基本信息页面开启关闭logagent 和 prometheus；
2、关闭prometheus兼容monitor和platform版本，开启prometheus默认开启monitor新版
3、从扩展组件移除prometheus
Fixes #
```release-note
```
```docs
```

feat(console):  can enable prometheus in cluster base info page

---

pkg/platform/proxy/extensions/ingress/storage/event.go

ingress apigroup replacement problem

---

pkg/util/apiclient/install.go

fix(cluster): yaml split error

---

api/registry/v1/conversion.go
pkg/registry/registry/chart/storage/storage.go
pkg/registry/registry/chartgroup/storage/storage.go
pkg/registry/util/chart.go
pkg/registry/util/chartgroup.go
web/console/src/modules/application/WebAPI.ts
web/console/src/modules/application/actions/project/listActions.ts
web/console/src/modules/registry/WebAPI.ts
web/console/src/modules/registry/actions/project/listActions.ts

>
> /kind bug
send projectid when request app list

fix(registry): send projectid when request app list

---

go.mod
go.sum

>
/kind bug
> /kind design
> /kind flake
Synchronize official bug fixes: https://github.com/docker/distribution/commit/0a1e4a57e241ac320b613a7d055ce166c9bb65f1
Fixes #734
```release-note
```
```docs
```

fix(registry): update dependence version of github.com/docker/distribution to fix a crash bug

---

web/console/src/modules/cluster/components/scale/common/hooks/useNamespaces.ts
web/console/src/modules/cluster/components/scale/cronhpa/editor/hpa.tsx
web/console/src/modules/cluster/components/scale/hpa/editor/hpa.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): hpa.tsx type error

---

web/console/src/modules/alarmPolicy/actions/projectNamespaceActions.project.ts
web/console/src/modules/logStash/components/LogStashActionPanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): fix logaent page error and project platform prometheus plug status display error

---

web/console/config/resource/k8sConfig/deployment.ts
web/console/config/resource/k8sConfig/tapp.ts
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerNumPanel.tsx
web/console/src/modules/cluster/components/scale/cronhpa/detail/basic.tsx
web/console/src/modules/cluster/components/scale/cronhpa/editor/hpa.tsx
web/console/src/modules/cluster/components/scale/cronhpa/list/index.tsx
web/console/src/modules/cluster/components/scale/cronhpa/list/namespaceSelect.tsx
web/console/src/modules/cluster/components/scale/hpa/constant.ts
web/console/src/modules/cluster/components/scale/hpa/detail/basic.tsx
web/console/src/modules/cluster/components/scale/hpa/editor/hpa.tsx
web/console/src/modules/cluster/components/scale/hpa/list/index.tsx
web/console/src/modules/cluster/components/scale/hpa/list/namespaceSelect.tsx

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: fix hpa and cronhpa problem
http://tapd.oa.com/tke_stack/prong/stories/view/1020425127860302539?url_cache_key=105a258ae3885799599ea928de076c6a&action_entry_type=story_tree_list  -- P0
Fixes #
```release-note
```
```docs
```

fix(cluster): fix hpa and cronhpa problem

---

pkg/monitor/controller/prometheus/controller.go
pkg/monitor/controller/prometheus/yamls.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/yamls.go

add more metrics for k8s node
Fixes #
```release-note
```
```docs
```

feat(platform,monitor): add more metrics for k8s node

---

docs/design-proposals/hostname-as-nodename-support.md

Fixes #
```release-note
```
```docs
```

fix(doc): use correct name

---

pkg/monitor/controller/prometheus/controller.go
pkg/monitor/controller/prometheus/yamls.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/addon/prometheus/yamls.go

add more metrics for k8s node and  cluster
Fixes #
```release-note
```
```docs
```

Prometheu: add more metrics

---

web/console/src/modules/cluster/components/scale/cronhpa/editor/hpa.tsx
web/console/src/modules/cluster/components/scale/hpa/editor/hpa.tsx

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: fix cronhpa edit problem
Fixes #
```release-note
```
```docs
```

fix(cluster): fix cronhpa edit problem

---

api/platform/cluster.go
api/platform/v1/cluster.go
cmd/tke-gateway/app/config/config.go
go.mod
go.sum
pkg/apiserver/openapi/openapi.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/machine/machine_controller.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/machine/kubeadm.go
pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/types/types.go
pkg/platform/types/v1/types.go
pkg/platform/util/client.go
pkg/util/apiclient/idempotency.go
pkg/util/ssh/ssh.go
test/e2e/certs/certs.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): ipv6 single stack support

---

CONTRIBUTING.md

[/CONTRIBUTING.md](https://github.com/tkestack/tke/blob/master/CONTRIBUTING.md)
Correct words.
Fixes #
No
```release-note
Correct words.
```
```docs
```

docs:correct words

---

pkg/business/registry/util/auth.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(business): remove first member from projects' members in portal

---

pkg/auth/controller/group/deletion/grouped_resources_deleter.go
pkg/auth/controller/localidentity/deletion/localidentity_resources_deleter.go
pkg/auth/registry/user/storage/project.go
pkg/auth/util/adapter.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(auth): update load casbin model from rule

---

pkg/platform/controller/cluster/cluster_controller.go

fix(cluster): anno or label modified but not updated

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): tke-gateway pods pull image failed by all-one

---

cmd/tke-installer/app/installer/certs/certs.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/installer.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go
test/e2e/certs/certs.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): limit the permissions of the certificates in webhook

---

web/console/src/modules/cluster/components/scale/hpa/constant.ts
web/console/src/modules/cluster/components/scale/hpa/detail/basic.tsx

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**:  bug fix
**Which issue(s) this PR fixes**: hpa details can not show bug
Fixes #
```release-note
```
```docs
```

fix(cluster): hpa details can not show bug

---

.github/workflows/build-web.yml
build/lib/web.mk

>
Fixes #
```release-note
```
```docs
```

feat(ci): add Node.js version check

---

pkg/notify/controller/messagerequest/util/util.go

> /kind bug
notify controller send sms to tencent cloud sms api, but got errors: x509: certificate signed by unknown authority.
This pr fix it
Fixes #585
```release-note
```
```docs
```

fix(notify): fix notify x509 certificate error

---

pkg/platform/provider/baremetal/validation/cluster.go

fix https://github.com/tkestack/tke/issues/638
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): don't allow service cidr is empty when enable ipvs

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/provider/cluster/interface.go

fix(cluster): resourceversion update not need to enqueue

---

web/installer/.babelrc
web/installer/package-lock.json
web/installer/package.json

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): fix babel runtime error

---

cmd/tke-platform-controller/app/options/options.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/types/v1/types.go

/kind feature
fix https://github.com/tkestack/tke/issues/853
fix https://github.com/tkestack/tke/issues/854

 randomlize cluster heartbeat

---

.github/workflows/e2e.yml
test/e2e/certs/certs.go
test/e2e/platform/platform_test.go
test/e2e/tke/tke.go
test/e2e_installer/bootstrap_test.go
test/util/client/client.go
test/util/cloudprovider/tencent/tencent.go
test/util/cmd.go
test/util/env/env.go
test/util/strings.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat: add smoke test

---

pkg/platform/controller/cluster/cluster_controller.go

fix(cluster): enqueue no immedutely when delete cluster

---

cmd/tke-gateway/app/config/config.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
cmd/tke-installer/app/installer/types/types.go
cmd/tke-registry-api/app/config/config.go
pkg/gateway/proxy/proxy.go
pkg/registry/apis/config/types.go
pkg/registry/apis/config/v1/types.go
pkg/registry/apis/config/v1/zz_generated.conversion.go
pkg/registry/apiserver/apiserver.go
pkg/registry/harbor/handler/proxy.go
pkg/registry/harbor/harbor.go

tke-gateway: add ignore auth /services/
tke-installer: add harborEnabled and harborCAFile
tke-registry-api:
support https based harbor as storage backend
registry image push and pull proxy
TODO:
registry and chart management api
chart upload and pull proxy
/kind feature

feat(registry): Add harbor registry proxy

---

.github/workflows/e2e.yml
test/e2e/platform/platform_test.go
test/e2e/tke/tke.go
test/util/cloudprovider/tencent/tencent.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix: remove the condition to build image

---

build/docker/tools/tke-installer/Dockerfile

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): support devcloud

---

pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/cluster/update.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix(cluster): lost apiserver cert (#875)

---

web/console/README.md

>
Fixes #
```release-note
```
```docs
```

feat(console): add readme

---

.github/workflows/e2e.yml

/kind feature
Fixes #884 
```release-note
```
```docs
```

fix: comment out one job

---

.github/workflows/e2e.yml

Revert "fix: comment out one job"

---

.github/workflows/e2e.yml

/kind bug
Fixes #884
```release-note
```
```docs
```

fix: update e2e workflow platform

---

pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #886 
```release-note
```
```docs
```

fix(platform): compatible webhook's certificate and private key

---

web/console/src/modules/uam/components/user/list/UserTablePanel.tsx

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**:  fix isssue
**Which issue(s) this PR fixes**: https://github.com/tkestack/tke/issues/810
Fixes #
```release-note
```
```docs
```

fix(uam): open admin pwd modify

---

pkg/spec/spec.go
web/console/src/modules/cluster/WebAPI/ClusterAPI.ts

/kind feature
Fixes #
```release-note
```
```docs
```

feat(platform): support k8s 1.17.13

---

pkg/gateway/proxy/proxy.go
pkg/registry/apis/config/v1/types.go
pkg/registry/apiserver/apiserver.go
pkg/registry/harbor/harbor.go
pkg/registry/harbor/tenant/tenant.go

1, add harbor chart upload and download proxy
2, add tke tenant for harbor registry and chart
kind feature

feat(registry): add harbor chart proxy and inject tenant

---

docs/guide/zh-CN/best-practices/jenkins.md

docs: update instructions

---

Makefile
build/docker/tools/provider-res/Makefile
build/docker/tools/tke-installer/release.sh
cmd/tke-installer/app/installer/images/images.go
pkg/spec/spec.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(ci): build provider res in ci

---

cmd/tke-installer/app/installer/installer.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(installer): patch k8s versions

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(ci): fix build failed issue

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go

1. enable auth webhook
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): enable auth webhook for master scale issue

---

pkg/monitor/util/cache/cache.go
pkg/monitor/util/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(monitor): fixed request and limit statistics

---

cmd/tke-installer/app/installer/installer.go

fix(registry): fix prepare registry certificate panic

---

web/console/src/modules/cluster/components/clusterManage/ConfigPromethus/index.tsx
web/console/src/webApi/promethus.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): fix config promethus params error

---

pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): idempotent problem

---

web/console/public/webtty.html

添加了显示webconsole的连接状态，明确是否可用。
Fixes #
```release-note
```
```docs
```

feat(console): show the connect status of webconsole

---

pkg/auth/registry/localidentity/storage/password.go
pkg/auth/registry/localidentity/storage/storage.go
pkg/auth/util/admin.go
pkg/auth/util/user.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(auth): limit action of changing user's password

---

web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/validateClusterCreationAction.ts
web/console/src/modules/cluster/components/KubectlDialog.tsx
web/console/src/modules/cluster/components/clusterManage/CreateClusterPanel.tsx
web/console/src/modules/cluster/components/clusterManage/KubeconfigFileParse.tsx
web/console/src/modules/cluster/models/ClusterCreationState.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): support import cluster from kubeconfig

---

web/console/src/modules/cluster/components/resource/nodeManage/UpdateNodeTaintDialog.tsx

>
> /kind bug
enable to delete node taint.
https://github.com/tkestack/tke/issues/816

fix(console): enable to delete node taint

---

web/console/lib/ff-redux/libs/qcloud-redux-query/lib/Query.ts
web/console/lib/ff-redux/src/base/Model/QueryState.ts
web/console/src/modules/cluster/actions/resourcePodActions.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceDetail.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodTable.tsx
web/console/src/modules/cluster/models/Pod.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): support pod paging and query

---

docs/design-proposals/webkubectl.md

fix document markdown style.
Fixes #
```release-note
```
```docs
```

fix(console):update the doc of webkubectl

---

api/platform/v1/types.go
api/platform/validation/cluster.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/provider/baremetal/cluster/delete.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
pkg/platform/provider/cluster/interface.go

1. decouple cluster update to housekeeping, upgrade, master scale up/down
2. implement master scale down: remove etcd mamber and k8s node
3. add validation: only ha mode support master scale
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): enhance cluster controller

---

web/console/public/webtty.html

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): fix webtty tips no hidden

---

web/console/src/modules/alarmPolicy/constants/Config.ts
web/console/src/modules/cluster/actions/validateWorkloadActions.ts
web/console/src/modules/cluster/models/MonitorPanel.tsx

>
> /kind bug
https://github.com/tkestack/tke/issues/774
Fixes #
```release-note
```
```docs
```

fix(console): nfs path enable use url and memory use no-cache

---

api/platform/validation/cluster.go
pkg/platform/controller/cluster/cluster_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): only validate ha for mater scale case

---

pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): path annotation to all master

---

cmd/tke-application-api/app/config/config.go

>
> /kind bug
fix(application): enable to disable registry client when startup

fix(application): enable to disable registry client

---

docs/design-proposals/smoke-and-release-test.md
test/e2e/platform/platform_test.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix: ensure instances delete operations to be executed

---

pkg/platform/provider/baremetal/cluster/update.go
pkg/platform/provider/baremetal/machine/update.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(platform): add label value for frontend

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/machine/kubeadm.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(cluster): add node-ip for kubelet

---

pkg/platform/provider/baremetal/cluster/update.go
pkg/platform/provider/baremetal/machine/update.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): upgrade reconcile time out

---

web/console/src/modules/cluster/actions/resourcePodActions.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodTable.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): change metadata.labels to spec.selector.matchlabels

---

pkg/platform/controller/addon/persistentevent/persistentevent_controller.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): persistent envent flaw

---

web/console/src/modules/cluster/actions/resourcePodActions.ts
web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx
web/console/src/modules/cluster/components/clusterManage/ConfigPromethus.tsx
web/console/src/modules/cluster/components/clusterManage/WorkerUpdate.tsx
web/console/src/modules/common/layouts/AntdLayout.tsx

>
> /kind bug
1、fix promethus default config;
2、when cluster is imported. don't show upgrade button
3、fix worker update button alway is disable
Fixes #
```release-note
```
```docs
```

fix(console): 1.5.0-alpha bug fix

---

build/docker/tools/tke-installer/install.sh
cmd/tke-installer/app/installer/installer.go

fix(installer): check container status
/kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): get flag from shell

---

web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
Enable tapp monitor
```
```docs
```

feat(console): enable tapp monitor

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/delete.go
pkg/util/apiclient/version.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): patch annotation according to k8s version

---

web/console/src/modules/addon/components/AddonHeadPanel.tsx
web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
web/console/src/modules/cluster/actions/resourceActions.ts
web/console/src/modules/cluster/components/clusterManage/ConfigPromethus.tsx
web/console/src/modules/cluster/components/clusterManage/WorkerUpdate.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/UpdateWorkloadRegistryPanel.tsx
web/console/src/modules/cluster/models/ResourceOption.ts
web/console/src/modules/registry/WebAPI.ts
web/console/src/modules/registry/components/chartgroup/create/BaseInfoPanel.tsx
web/console/src/webApi/cluster.ts
web/installer/src/modules/installer/actions/validateActions.ts
web/installer/src/modules/installer/components/Step8.tsx

>
> /kind bug
1.only running worker can upgrade;
2.install page check console domain;
3.config promethus add more rules;
4.workerload support use labels querry;
5.addon cluster list search able;
6. adjust change image input width;
7. fix passworld length display error
Fixes #
```release-note
```
```docs
```

fix(console): 1.5.0 alpha 2020 12 03

---

web/console/src/modules/addon/components/AddonHeadPanel.tsx
web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
web/console/src/modules/cluster/actions/resourcePodActions.ts
web/console/src/modules/cluster/components/clusterManage/ClusterUpdate.tsx
web/console/src/modules/cluster/constants/Config.ts
web/console/src/webApi/cluster.ts
web/installer/src/modules/installer/actions/validateActions.ts

>
> /kind bug
1. fix pod query labelSelector lost
Fixes #
```release-note
```
```docs
```

fix(console): 1.5.0-alpha 2020-12-04

---

web/console/src/modules/cluster/actions/resourcePodActions.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodPanel.tsx
web/console/src/modules/cluster/models/Pod.ts

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): support terminating status and evicted reason show

---

web/console/src/modules/notify/components/resourceEdition/EditResource.tsx
web/console/src/modules/notify/components/resourceList/ResourceTableChannel.tsx

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): webhook notification template fixed

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/installer_test.go
cmd/tke-installer/app/installer/manifests/tke-gateway/tke-gateway.yaml
pkg/util/template/template.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(installer): support certificate chain

---

web/console/src/modules/notify/components/resourceEdition/EditResource.tsx

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): spec for notification channel creation fixed

---

web/console/src/modules/cluster/actions/resourcePodActions.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): clear pod name query not reset pagesize

---

web/console/src/modules/notify/components/resourceEdition/EditResourceTemplate.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): when update notify disable Channels selecter

---

pkg/platform/provider/baremetal/images/images.go

fix(platform): upgrade gpu-manager version to fix one node with multi gpu cause gpu-manager crash
What type of PR is this?
Uncomment only one /kind <> line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind api-change
/kind bug
/kind cleanup
/kind deprecation
/kind design
/kind failing-test
/kind feature
/kind flake
What this PR does / why we need it:
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:

fix(platform): one node with multi gpu cause gpu-manager crash

---

charts/tke-auth-api/templates/configmap.yaml
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/etcd/etcd.yaml
cmd/tke-installer/app/installer/manifests/tke-application-api/tke-application-api.yaml
cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml
cmd/tke-installer/app/installer/manifests/tke-business-api/tke-business-api.yaml
cmd/tke-installer/app/installer/manifests/tke-logagent-api/tke-logagent-api.yaml
cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
cmd/tke-installer/app/installer/manifests/tke-notify-api/tke-notify-api.yaml
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
pkg/platform/provider/baremetal/cluster/provider.go

fix https://github.com/tkestack/tke/issues/987
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): update etcd ep automatically

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): etcd file not found

---

web/console/src/modules/cluster/actions/validateSecretActinos.ts

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): validation of a valid secret config key fixed

---

build/docker/tools/provider-res/Makefile
build/docker/tools/tke-installer/release.sh
cmd/tke-installer/app/installer/images/images.go
pkg/spec/spec.go
web/installer/src/modules/installer/components/Step3.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform):support docker 19.03.14

---

cmd/tke-application-api/app/config/config.go
cmd/tke-audit-api/app/config/config.go
cmd/tke-auth-api/app/config/config.go
cmd/tke-business-api/app/config/config.go
cmd/tke-gateway/app/config/config.go
cmd/tke-gateway/app/server.go
cmd/tke-logagent-api/app/config/config.go
cmd/tke-monitor-api/app/config/config.go
cmd/tke-notify-api/app/config/config.go
cmd/tke-platform-api/app/config/config.go
cmd/tke-registry-api/app/config/config.go
pkg/apiserver/handler/chain.go
pkg/auth/filter/filter.go
pkg/auth/filter/inspector.go
pkg/platform/registry/cluster/strategy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(all): fix cross tenants errors

---

pkg/platform/registry/cluster/storage/addon_type.go
pkg/platform/registry/clusteraddontype/const.go
pkg/platform/registry/clusteraddontype/storage/cluster_addon_type.go

> /kind refactor
addon type support more customization, now those addon types can not customization,like labels etc..
no
```release-note
no
```
```docs
no
```

refactor(platform): addon type support more customization

---

pkg/platform/registry/clusteraddontype/storage/cluster_addon_type.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): fix problem of applying addon slice

---

pkg/auth/filter/filter.go
pkg/auth/filter/inspector.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth,platform): allow create clusters in inspectors

---

pkg/platform/provider/baremetal/cluster/kubeadm.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): add IPVS.ExcludeCIDRs

---

pkg/util/ssh/ssh.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): ssh support ChallengeResponseAuthentication

---

build/docker/tools/provider-res/Dockerfile
build/docker/tools/provider-res/download.sh
pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
pkg/platform/provider/baremetal/res/res.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(platform): remove kubeadm packge

---

cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/prepare.go
cmd/tke-installer/app/installer/upgrader.go
cmd/tke-installer/app/options/options.go
docs/guide/zh-CN/best-practices/offline-pot/install-tke-installer.sh
pkg/util/docker/docker.go
pkg/util/version/version_test.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(installer): support custom k8s upgrade

---

cmd/tke-installer/app/installer/upgrader.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): patch version for install global

---

docs/guide/zh-CN/best-practices/custom-k8s-version-upgrade.md

Fixes #
```release-note
```
```docs
```

docs: update custom upgrade

---

pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/util/version.go

Fixes #
```release-note
```
```docs
```

feat(platform): support deploy custom k8s

---

docs/guide/zh-CN/best-practices/custom-k8s-version-upgrade.md

Fixes #
```release-note
```
```docs
```

docs: 1.16.x coreDNS problem

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/prepare.go
cmd/tke-installer/app/installer/upgrader.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(installer): support prepare unofficial k8s

---

cmd/tke-installer/app/installer/installer.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): nil globalclient case

---

cmd/tke-installer/app/installer/installer.go
pkg/spec/spec.go

/kind bug
Fixes #
```release-note
```
```docs
```

Move patchversion loc1.5

---

pkg/platform/provider/baremetal/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): upgrade busybox image

---

pkg/platform/provider/baremetal/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): upgrade busybox image on master

---

pkg/spec/spec.go

/kind bug
Fixes #1046
```release-note
```
```docs
```

fix(installer): tke version is empty

---

build/docker/tools/tke-installer/install.sh

/kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): delet custom resource first time

---

docs/guide/zh-CN/best-practices/renewing-kubernetes-certificates.md

Fixes #
```release-note
```
```docs
```

docs: renewing k8s certs

---

pkg/platform/controller/addon/gpumanager/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): update gpu-manager to v1.0.4

---

build/docker/tools/provider-res/Makefile
build/docker/tools/tke-installer/release.sh
cmd/tke-installer/app/installer/images/images.go
pkg/spec/spec.go
web/installer/src/modules/installer/components/Step3.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support docker 19.03.14 (#999)

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/cluster/util.go
pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/machine/provider.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/installer/src/modules/installer/components/Step2.tsx
web/installer/src/modules/installer/reducers/initState.ts

/kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): intranet IP lb loopback

---

build/docker/tools/provider-res/Makefile
build/docker/tools/tke-installer/release.sh
cmd/setup-env/main.go
cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/prepare.go
cmd/tke-installer/app/installer/upgrader.go
pkg/platform/provider/baremetal/images/images.go
pkg/platform/provider/baremetal/res/res.go
pkg/spec/spec.go
pkg/util/apiclient/client_test.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(platform): update support k8s to 1.19.7

---

build/docker/tools/provider-res/Makefile
build/docker/tools/tke-installer/release.sh
cmd/setup-env/main.go
cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/prepare.go
cmd/tke-installer/app/installer/upgrader.go
pkg/platform/provider/baremetal/images/images.go
pkg/platform/provider/baremetal/res/res.go
pkg/spec/spec.go
pkg/util/apiclient/client_test.go

Reverts tkestack/tke#1064
comments: it break daily build, when the  e2e test done, please help double merge, thanks @leoryu

Revert "feat(platform): update support k8s to 1.19.7"

---

cmd/tke-installer/app/installer/manifests/tke-audit-api/tke-audit-api.yaml

/kind bug
Fixes #
```release-note
```
```docs
```

fix(audit): typo

---

web/console/src/modules/cluster/components/resource/nodeManage/ComputerTablePanel.tsx

>
> /kind bug
https://github.com/tkestack/tke/issues/1066
Fixes #
```release-note
```
```docs
```

fix(console): node ip copy all is same

---

build/docker/tools/tke-installer/release.sh
build/lib/common.mk
build/lib/create-manifest.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(build): disable build arm

---

web/console/Wrapper.tsx
web/console/package.json
web/console/src/modules/common/components/tke-version/index.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): show version in left menu bottom

---

build/docker/tools/tke-installer/release.sh
build/lib/common.mk
build/lib/create-manifest.sh

Revert "feat(build): disable build arm"

---

.github/workflows/release.yml

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: update release.yml format

---

.github/workflows/e2e.yml
.github/workflows/release.yml

>
> /kind bug
/kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: update release and e2e workflow

---

.github/workflows/release.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
```
```docs
```

feat: manual trigger release build

---

build/docker/tools/tke-installer/release.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): echo current builder

---

pkg/notify/registry/receivergroup/strategy.go

> /kind bug
Receivers of receiver group may be deleted by users, check and remove them when updating receiver group
Fixes #
```release-note
```
```docs
```

fix(notify): remove not exist receivers in receiver group

---

.github/workflows/release.yml
test/e2e_installer/installer/installer_test.go
test/e2e_installer/node/node_test.go
test/tke/installer.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: update release ci and related tests

---

.github/workflows/release.yml

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: fix release.yml

---

test/tke/installer.go
test/util/client/client.go
test/util/cloudprovider/tencent/tencent.go
test/util/cmd.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: user internal IP (platform)

---

test/util/cloudprovider/tencent/tencent.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Refine create instance logic (platform)

---

docs/design-proposals/installer-thanos-support.md

/kind design
Fixes #
```release-note
```
```docs
```

docs(installer): thanos support to tke-installer design proposal

---

web/console/src/modules/cluster/actions/validateClusterCreationAction.ts

>
> /kind bug
https://github.com/tkestack/tke/issues/1073
Fixes #
```release-note
```
```docs
```

fix(console): remove certfile and token required rule

---

test/e2e_installer/node/node_test.go
test/tke/installer.go
test/util/cloudprovider/tencent/tencent.go
test/util/env/env.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: support instance type list (platform)

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/upgrader.go
pkg/platform/controller/addon/cronhpa/images/images.go
pkg/platform/controller/addon/tappcontroller/images/images.go
pkg/platform/types/v1/types.go

Fix https://github.com/tkestack/tke/issues/1117
Fixes #
```release-note
```
```docs
```

feat(installer): update tapp cronhpa when upgrade

---

cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/thanos/manifest_test.go
cmd/tke-installer/app/installer/manifests/thanos/thanos.yaml
cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
cmd/tke-installer/app/installer/manifests/tke-monitor-controller/tke-monitor-controller.yaml
cmd/tke-installer/app/installer/types/types.go
pkg/monitor/controller/prometheus/controller.go

/kind feature
Fixes #1100
```release-note
NONE
```
```docs
```

feat(installer): add thanos support to tke-installer

---

pkg/monitor/util/cache/cache.go
pkg/monitor/util/types.go

…o k8s 1.19
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(monitor): check components' status to adapt to k8s 1.19

---

cmd/tke-installer/app/installer/upgrader.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): upgrade monitor during upgrade

---

web/console/helpers/request.ts
web/console/package.json
web/console/src/modules/addon/actions/validatorActions.ts
web/console/src/modules/cluster/actions/clusterActions.ts
web/console/src/modules/cluster/components/KubectlDialog.tsx
web/console/src/modules/cluster/components/clusterManage/ClusterUpdate.tsx
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/console/src/modules/logStash/actions/validatorActions.ts
web/console/src/modules/persistentEvent/actions/validatorActions.ts
web/console/src/modules/registry/components/chartgroup/create/BaseInfoPanel.tsx
web/console/src/modules/registry/constants/ChartGroupValidateConfig.ts
web/console/src/modules/uam/components/user/create/UserCreate.tsx

>
> /kind bug
1、fix when upgrade master, back to cluster list page , status not auto refresh;
2、fix when checkout VIP type, ip address not clean;
3、fix when create cluster success, quickly open info ,get blank page;
4、add special error response compatible;
5、fix when not choose custom not hidden transfer
6、fix Elasticsearch path error tip not right
7、fix when not support monitor, cluster list page get error;
8、add third mirror input validate;
Fixes #
```release-note
```
**Additional …

fix(console): release 1.6 UI bug fix

---

web/console/src/modules/alarmPolicy/components/EditAlarmPolicyPanel.tsx
web/console/src/modules/alarmPolicy/models/AlarmPolicy.ts
web/console/src/modules/notify/components/resourceEdition/EditResource.tsx
web/console/src/modules/notify/schema/channelSchema.ts

>
> /kind bug
1、add validator for alarm webhook url;
2、add validator for alarm notify way;
Fixes #
```release-note
```
```docs
```

fix(console): bug fix for release 1.6 on 03.17

---

pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go

>
> /kind design
> /kind flake
/kind bug
Fixes #1138
```release-note
```
```docs
```

fix(platform): fix WebHookCertAndKeyExist function path error (#1138)

---

pkg/platform/provider/baremetal/cluster/kubeadm.go

fix https://github.com/tkestack/tke/issues/1090
Fixes #
```release-note
```
```docs
```

fix(platform): fix anonymous auth

---

web/console/package.json

>
> /kind bug
because react-redux version update, make build faild
Fixes #
```release-note
```
```docs
```

fix(console): locked react-redux version

---

pkg/auth/filter/inspector.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): allow cross-tenant access to clusters

---

charts/tke-auth-api/templates/configmap.yaml
cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml
pkg/apiserver/authorization/abac/abac.go
pkg/apiserver/filter/authentication.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Fix anonymous users

---

pkg/platform/provider/baremetal/cluster/kubeadm.go

Revert "fix(platform): fix anonymous auth"

---

cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): api yaml format err

---

charts/tke-auth-api/templates/configmap.yaml
cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(auth): reset abac policy

---

CHANGELOG/CHANGELOG-1.5.md

update 1.5.1 changelog
Fixes #
```release-note
```
```docs
```

docs: update 1.5.1 changelog

---

pkg/apiserver/authentication/authenticator/apikey/apikey.go
pkg/registry/chartmuseum/authentication/authentication.go
pkg/registry/distribution/auth/auth.go
pkg/registry/util/authentication/authentication.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(registry): modify password to request auth

---

pkg/util/apiclient/client.go

/kind feature
fix https://github.com/tkestack/tke/issues/1080
Fixes #
```release-note
```
```docs
```

feat(platform): stop using ListWatchUtil

---

cmd/tke-application-api/app/options/options.go
cmd/tke-auth-api/app/options/options.go
cmd/tke-business-api/app/options/options.go
cmd/tke-logagent-api/app/options/options.go
cmd/tke-mesh-api/app/options/options.go
cmd/tke-monitor-api/app/options/options.go
cmd/tke-notify-api/app/options/options.go
cmd/tke-platform-api/app/options/options.go
cmd/tke-registry-api/app/options/options.go
pkg/apiserver/options/generic.go

/kind feature
fix https://github.com/tkestack/tke/issues/1081
Fixes #
```release-note
```
```docs
```

feat(platform): remove TargetRAMM

---

pkg/platform/proxy/store.go

/kind feature
Fixes https://github.com/tkestack/tke/issues/1083
```release-note
```
```docs
```

feat(platform): stop using internalversion

---

pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm_test.go

/kind bug
Identify version inc info, eg. 1.20.4 != 1.20.4.tke.
Fixes #
```release-note
```
```docs
```

fix(platform): identify version inc info

---

web/console/.npmrc
web/console/package-lock.json
web/console/package.json

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): add package-lock.json

---

build/docker/tools/provider-res/Makefile
build/docker/tools/tke-installer/release.sh
cmd/tke-installer/app/installer/images/images.go
pkg/spec/spec.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add 1.20.4 tke

---

pkg/spec/spec.go
test/e2e_installer/cluster/cluster_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(test): update test for k8s 1.20.4

---

test/tke/tke.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(test): retry create cluster in e2e test

---

web/console/helpers/version.ts

>
> /kind bug
import compare-versions wrong,
The actual method is inconsistent with the official reademe
Fixes #
```release-note
```
```docs
```

fix(console): import package wrong

---

.github/workflows/e2e.yml
test/e2e/constants.go
test/e2e/manifests/docker/config.json
test/tke/tke.go
test/util/env/env.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(test): use githubactions dokcer auth

---

pkg/platform/controller/cluster/cluster_controller.go

kind bug
Fixes #1179 
```release-note
NONE
```
<!--
This section can be blank if this pull request does not require a release note.
When adding links which point to resources within git repositories, like
KEPs or supporting documentation, please reference a specific commit and avoid
linking directly to the master branch. This ensures that links reference a
specific point in time, rather than a document that may change over time.
See here for guidance on getting permanent links to files: …

fix(platform): set ownerreference for imported cluster credentials

---

web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx
web/console/src/modules/registry/components/chart/ChartTablePanel.tsx

> /kind bug
Fixes #1180 
```release-note
NONE
```
<!--
This section can be blank if this pull request does not require a release note.
When adding links which point to resources within git repositories, like
KEPs or supporting documentation, please reference a specific commit and avoid
linking directly to the master branch. This ensures that links reference a
specific point in time, rather than a document that may change over time.

fix(webconsole): install helm v3

---

test/tke/tke.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(test): wait cluster condition with more time

---

cmd/tke-installer/app/installer/chart.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): push chart with force flag

---

web/console/helpers/format.ts
web/console/helpers/index.ts
web/console/src/modules/cluster/components/resource/nodeManage/ComputerActionPanel.tsx
web/console/src/modules/cluster/components/resource/nodeManage/ComputerTablePanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNodeDetailPanel.tsx

>
> /kind bug
Fixes #
fix https://github.com/tkestack/tke/issues/1207
```release-note
```
```docs
```

fix(console): virtual node cpu&memory display wrong

---

web/console/README.md

>
Fixes #
```release-note
```
```docs
```

feat(doc): add replace service web static file doc

---

web/console/helpers/format.ts
web/console/src/modules/cluster/components/resource/nodeManage/ComputerActionPanel.tsx
web/console/src/modules/cluster/components/resource/nodeManage/ComputerTablePanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNodeDetailPanel.tsx

>
> /kind bug
Fixes #
fix https://github.com/tkestack/tke/issues/1219
```release-note
```
```docs
```

fix(console): fix  some attribute  not have , let ui error

---

Makefile
build/docker/tools/provider-res/download.sh
build/lib/docker-buildx.mk
build/lib/image.mk

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(ci): build images without buildkit

---

.github/workflows/e2e.yml
.github/workflows/release.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(ci): add env from esecret in release test

---

web/installer/src/modules/installer/components/Step5.tsx
web/installer/src/modules/installer/reducers/initState.ts

>
Fixes #
fix https://github.com/tkestack/tke/issues/1227
```release-note
```
```docs
```

feat(installer): set install application store as default

---

pkg/application/controller/app/action/rollback.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): fix helm rollback failed reversion fill error

---

cmd/tke-platform-controller/app/run.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/provider/cluster/interface.go

1. add informer filter
2. support cusomized controller name
fix https://github.com/tkestack/tke/issues/1228
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): refine cluster controller

---

docs/design-proposals/cilium.md
docs/yamls/cilium/cilium-ha.yaml
docs/yamls/cilium/cls-clb.json
docs/yamls/cilium/cls-vip.json

Fixes #
```release-note
```
```docs
```

docs(design-proposal): add cilium HA case

---

build/docker/tools/tke-installer/init_installer.sh

fix https://github.com/tkestack/tke/issues/1218
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): improve installer deploy speed

---

.github/workflows/e2e.yml
.github/workflows/release.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(ci): add INSTANCE_TYPES for ci test

---

.github/workflows/e2e.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): test env

---

cmd/tke-platform-api/apiserver.go
cmd/tke-platform-controller/controller-manager.go
pkg/platform/provider/registered/cluster/create.go
pkg/platform/provider/registered/cluster/delete.go
pkg/platform/provider/registered/cluster/provider.go
pkg/platform/provider/registered/validation/cluster.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): support new registered cluster type

---

.github/workflows/e2e.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): remove env test

---

.github/workflows/e2e.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): use secret not secrests to get env

---

.github/workflows/e2e.yml

Revert "feat(ci): use secret not secrests to get env"

---

.github/workflows/e2e.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): add env info

---

.github/workflows/e2e.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): test pull request target

---

.github/workflows/e2e.yml

Revert "feat(ci): test pull request target"

---

web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/createICAction.ts
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/console/src/modules/cluster/constants/ActionType.ts
web/console/src/modules/cluster/constants/Config.ts
web/console/src/modules/cluster/models/CreateIC.ts
web/console/src/modules/cluster/reducers/CreateICReducer.ts
web/installer/src/modules/installer/WebAPI.ts

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): support cilium

---

cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): use v1 instead of v1beta1 in yaml

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/phases/galaxy/galaxy.go
pkg/platform/provider/baremetal/util/util.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): clean cilium net before install

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1163
```release-note
```
```docs
```

fix(installer): modify procedure description

---

README.md

docs(readme): bump installer version to v1.6.0
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs(readme): bump installer version to v1.6.0

---

build/docker/tools/tke-installer/install.sh
cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/chart.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/prepare.go
cmd/tke-installer/app/installer/upgrader.go
cmd/tke-installer/app/options/options.go

/kind flake
Fixes https://github.com/tkestack/tke/issues/1176
```release-note
```
```docs
```

feat(installer): support push custom charts

---

cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/expansion.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/examples/expansions/README.md
cmd/tke-installer/examples/expansions/hooks/post-cluster-ready
cmd/tke-installer/examples/expansions/hooks/post-install
cmd/tke-installer/examples/expansions/hooks/pre-install

/kind feature
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer,platform): expansion-framework support

---

cmd/tke-installer/app/installer/manifests/tke-application-api/tke-application-api.yaml
cmd/tke-installer/app/installer/manifests/tke-application-controller/tke-application-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-audit-api/tke-audit-api.yaml
cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml
cmd/tke-installer/app/installer/manifests/tke-auth-controller/tke-auth-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-business-api/tke-business-api.yaml
cmd/tke-installer/app/installer/manifests/tke-business-controller/tke-business-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-logagent-api/tke-logagent-api.yaml
cmd/tke-installer/app/installer/manifests/tke-logagent-controller/tke-logagent-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-mesh-api/tke-mesh-api.yaml
cmd/tke-installer/app/installer/manifests/tke-mesh-controller/tke-mesh-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
cmd/tke-installer/app/installer/manifests/tke-monitor-controller/tke-monitor-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-notify-api/tke-notify-api.yaml
cmd/tke-installer/app/installer/manifests/tke-notify-controller/tke-notify-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-controller/tke-registry-controller.yaml

/kind feature
Fixes https://github.com/tkestack/tke/issues/1113
```release-note
```
```docs
```

feat(installer): schedule tke com to master/controle-plane node

---

api/platform/validation/cluster.go

/kind bug
Fixes https://github.com/tkestack/tke/issues/1159
```release-note
```
```docs
```

fix(platform, installer): handle file not exist in ValidateHooks

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1278
```release-note
```
```docs
```

fix(installer): revise patch platform version log

---

pkg/platform/provider/baremetal/phases/kubelet/kubelet.go
pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): backup file failed

---

pkg/util/ssh/ssh.go

> /kind bug
fix write remote file bugs when installing tkestack
Fixes #1296

fix(platform): fix ssh write file bug (#1296)

---

web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/createICAction.ts
web/console/src/modules/cluster/actions/validateCreateICAction.ts
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/console/src/modules/cluster/constants/ActionType.ts
web/console/src/modules/cluster/constants/Config.ts
web/console/src/modules/cluster/models/CreateIC.ts
web/console/src/modules/cluster/reducers/CreateICReducer.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): support select networkMode

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/machine/kubeadm.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add lable on master[0] for cilium underlay

---

pkg/platform/provider/baremetal/manifests/cilium/eni-ipamd.yaml

fix https://github.com/tkestack/tke/issues/1311
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): fix eni ipamd yaml format error

---

pkg/platform/provider/baremetal/manifests/cilium/eni-ipamd.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform):  change parameter from string to int

---

cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml

fix(platform): fix rbac for platform-api

---

build/docker/tools/tke-installer/install.sh
build/docker/tools/tke-installer/release.sh
cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/options/options.go

fix(installer): fix REGISTRY_PREFIX not working

---

pkg/gateway/assets/assets.go

/kind feature
Fixes https://github.com/tkestack/tke/issues/1308
```release-note
```
```docs
```

feat(gateway): support gzip

---

pkg/monitor/controller/prometheus/images/images.go
pkg/platform/controller/addon/prometheus/images/images.go

/kind bug
Fixes https://github.com/tkestack/tke/issues/1305
```release-note
```
```docs
```

fix(monitor): apiserver report monitor related err

---

CHANGELOG/CHANGELOG-1.7.md
README.md

Fixes #
```release-note
```
```docs
```

docs: add v1.7.0 changelog

---

pkg/spec/spec.go

/kind bug
/kind feature
Fixes https://github.com/tkestack/tke/issues/1330
```release-note
```
```docs
```

feat(platform): set priority k8s version to 1.20.4

---

cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/application_test.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/expansion.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/upgrader.go
pkg/platform/types/v1/types.go

feat(installer,platform): support installing apps from charts
/kind feature
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer,platform): support installing apps from charts

---

docs/design-proposals/cilium.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs(design-proposal): update cilium doc

---

cmd/tke-platform-controller/app/options/clustercontroller.go
cmd/tke-platform-controller/app/options/options.go
cmd/tke-platform-controller/app/platform.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/config/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(cluster): export health check time to options

---

cmd/tke-installer/app/installer/chart.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/expansion.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/prepare.go
cmd/tke-installer/app/installer/upgrader.go

/kind feature
Fixes https://github.com/tkestack/tke/issues/1356
```release-note
```
```docs
```

feat(installer): push charts to diff repo

---

pkg/platform/controller/cluster/cluster_controller.go

> /kind bug
Fixes #1366
** What this PR does / why we need it**:
1. use informer to ensure sync cluster status
2.  the old code is meant to be compatible with the old version tke, and now is depreated: 
1. old version tke need label: [feat(platform): add machineIP to old nodes](https://github.com/tkestack/tke/commit/4d212248d55db454515dd32e06d96f50eb5c9737)
2. old version tke need credential: [support upgrade kubernetes](https://github.com/tkestack/tke/commit/c7703cc7950105379178317e57bee7e9d6cbdb87)

fix(platform):use informer to ensure sync cluster status(#1366)

---

docs/design-proposals/addon-framework-recap.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add proposal and use cases

---

docs/design-proposals/addon-framework-recap.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add undone proposals

---

docs/design-proposals/addon-framework-recap.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: change label build-in to built-in

---

cmd/tke-platform-controller/app/options/clustercontroller.go
cmd/tke-platform-controller/app/options/machinecontroller.go
cmd/tke-platform-controller/app/options/options.go
cmd/tke-platform-controller/app/platform.go
go.mod
go.sum
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/config/types.go
pkg/platform/controller/machine/config/types.go
pkg/platform/controller/machine/machine_controller.go

>
/kind feature
Fixes #
When too many resources are stuck in the process of creation, the default parameters of the workerqueue of the controller are filled. Exposure of this parameter can be optimized for the environment.
```release-note
```
```docs
```

feat(platform): export limiter  options

---

.github/workflows/e2e.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

test: cp provider conf for test

---

build/docker/tools/provider-res/download.sh
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/phases/containerd/containerd.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): fix yaml format error

---

web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/createICAction.ts
web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
web/console/src/modules/cluster/constants/ActionType.ts
web/console/src/modules/cluster/constants/Config.ts
web/console/src/modules/cluster/models/CreateIC.ts
web/console/src/modules/cluster/reducers/CreateICReducer.ts

>
允许创建集群时选择容器运行时类型
Fixes #
```release-note
```
```docs
```

feat(console): when create cluster enable select containerRuntime

---

cmd/tke-installer/app/installer/upgrader.go

/kind feature
Fixes https://github.com/tkestack/tke/issues/1175
```release-note
```
```docs
```

feat(installer): set check logic outermost layer

---

.github/workflows/e2e.yml
cmd/tke-installer/app/installer/upgrader.go
pkg/logagent/util/cluster.go
pkg/monitor/controller/prometheus/controller.go
pkg/monitor/util/cache/cache.go
pkg/platform/controller/addon/lbcf/controller.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/deletion/cluster_deleter.go
pkg/platform/controller/machine/deletion/machine_deleter.go
pkg/platform/controller/machine/machine_controller.go
pkg/platform/provider/cluster/cluster.go
pkg/platform/provider/cluster/interface.go
pkg/platform/proxy/client.go
pkg/platform/registry/cluster/storage/lbcf_backendgroup.go
pkg/platform/registry/cluster/storage/lbcf_backendrecord.go
pkg/platform/registry/cluster/storage/lbcf_loadbalancer.go
pkg/platform/registry/cluster/storage/tappcontroller.go
pkg/platform/registry/cluster/strategy.go
pkg/platform/types/types.go
pkg/platform/types/v1/types.go
pkg/platform/util/client.go
pkg/platform/util/location.go
test/cmd/tke-up/main.go
test/e2e/certs/certs.go
test/e2e/platform/platform_suite_test.go
test/e2e/platform/platform_test.go
test/e2e/tke/tke.go
test/tke/installer.go
test/tke/tke.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(platform): support custom credential getter

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): mount containerd network namespace into galaxy

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

Revert "fix(platform): mount containerd network namespace into galaxy"

---

Makefile
build/docker/tools/provider-res/Dockerfile
build/docker/tools/provider-res/download.sh
build/docker/tools/tke-installer/Dockerfile
build/docker/tools/tke-installer/install.sh
build/docker/tools/tke-installer/release.sh
cmd/setup-env/main.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/installer.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/conf/kubeadm/10-kubeadm.conf
pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/phases/containerd/containerd.go
pkg/platform/provider/baremetal/phases/image/image.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
pkg/spec/spec.go
pkg/util/docker/docker.go
test/e2e/manifests/tke-platform-controller/tke-platform-controller.yaml
test/e2e/tke/tke.go

Revert "feat(installer): support containerd installation"

---

build/docker/tools/provider-res/download.sh
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/phases/containerd/containerd.go

Revert "fix(installer): fix yaml format error"

---

pkg/application/controller/app/app_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): retry if app failed

---

web/console/.gitignore
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx

>
> /kind bug
fix: https://github.com/tkestack/tke/issues/1392
Fixes #
```release-note
```
```docs
```

fix(console): fix use search get error

---

pkg/application/registry/application/strategy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(application): allow user to define app name

---

pkg/audit/api/api.go

/kind bug
Add application.GroupName to controlPlaneGroups, or the applicattion group events will be filtered out.
Fixes #1474 
NONE
```docs
```

fix(audit): add application.GroupName to controlPlaneGroups

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/deletion/cluster_deleter.go
pkg/platform/controller/machine/deletion/machine_deleter.go
pkg/platform/controller/machine/machine_controller.go
pkg/platform/provider/baremetal/cluster/delete.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/machine/delete.go
pkg/platform/provider/baremetal/machine/provider.go

Revert "Revert "fix(platform): delete machine failed & move machine operation to provider""

---

pkg/platform/registry/cluster/storage/proxy.go

when the target cluster is global the user and tenantID need to be set in the header
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): compatible with certificate authentication

---

cmd/tke-installer/app/installer/installer.go

> /kind bug
Check console address is ip or not before add to SAN certs
Fixes #1307

fix(installer): add console ip to api server certSANs(#1307)

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/machine/machine_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): delete machine/cluster not found loop

---

pkg/platform/controller/bootstrapapps/controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): bootstrap not found loop

---

api/application/v1/conversion.go
pkg/application/registry/application/strategy.go

/kind bug
Fixes https://github.com/tkestack/tke/issues/1498
```release-note
```
```docs
```

fix(application): selector with targetNamespace

---

web/console/helpers/urlUtil.ts
web/console/package-lock.json
web/console/package.json
web/console/src/modules/application/WebAPI.ts
web/console/src/modules/registry/WebAPI.ts

fix: https://github.com/tkestack/tke/issues/1432
Fixes #
```release-note
```
```docs
```

feat(console): support get app from target namespace

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): set docker as global cls runtime

---

build/docker/tools/provider-res/Dockerfile
build/docker/tools/provider-res/Makefile
cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
pkg/platform/provider/baremetal/phases/containerd/containerd.go
test/e2e/manifests/tke-platform-controller/tke-platform-controller.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): remove containerd volume mount

---

cmd/tke-installer/app/installer/upgrader.go

> /kind bug
Init registry client before use it
Fixes #1511

fix(installer): init registryClient

---

Makefile

Revert "fix(platform): upgrade addon description"

---

build/docker/tools/provider-res/Dockerfile
build/docker/tools/provider-res/Makefile
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/conf/containerd/config.toml
pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/images/images.go
pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): fix gpu issue

---

build/docker/tools/provider-res/Dockerfile
build/docker/tools/provider-res/Makefile
build/docker/tools/tke-installer/release.sh
cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
pkg/platform/provider/baremetal/constants/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): remove cilium configmap

---

build/docker/tools/tke-installer/install.sh
pkg/platform/provider/baremetal/phases/containerd/containerd.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): fix install issue

---

pkg/platform/provider/baremetal/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1397
```release-note
```
```docs
```

feat(platform): upgrade eni ipamd to v3.3.3

---

pkg/platform/controller/cluster/cluster_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1506
```release-note
```
```docs
```

fix(platform): ensure create credential not idempotent

---

pkg/logagent/util/cluster.go
pkg/monitor/controller/prometheus/controller.go
pkg/monitor/util/cache/cache.go
pkg/monitor/util/cluster.go
pkg/platform/controller/addon/logcollector/controller.go
pkg/platform/util/addon/client.go
pkg/platform/util/addon/readme.md
pkg/platform/util/client.go

> /kind bug
Fixes #1540 
```release-note
```
```docs
```

fix(addon): decouple addon with provider

---

web/console/src/modules/cluster/reducers/CreateICReducer.ts

>
>
Fixes #
```release-note
```
```docs
```

feat(console): set container runtime default value as containerd

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): global cls use containerd

---

pkg/platform/provider/baremetal/cluster/kubeadm.go

> /kind bug
> /kind design
Fix coredns version to 1.7.0

feat(installer): coredns version is fixed to 1.7

---

web/console/src/modules/cluster/constants/Config.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): upgrade clear node sh

---

cmd/tke-installer/app/installer/upgrader.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): update need upgrade coms

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): check docker status before install

---

web/console/config/resource/k8sConfig/cronjobs.ts

>
> /kind bug
fix: https://github.com/tkestack/tke/issues/1574
Fixes #
```release-note
```
```docs
```

fix(console): remove history for cornjob detail

---

web/console/src/modules/cluster/components/resource/nodeManage/ComputerActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): when prometheus not installed disable the button

---

web/console/src/modules/cluster/components/resource/nodeManage/ComputerActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): disable monitor button when no monitor plug for 1.7release

---

web/console/src/modules/cluster/components/clusterManage/ClusterUpdate.tsx

>
> /kind bug
添加校验规则：master升级支持一个次版本升级到下一个次版本，或者同样次版本的补丁版。
Fixes #
```release-note
```
```docs
```

fix(console): add validate for upgrade master version

---

web/console/src/modules/cluster/constants/Config.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): update clearNodeSH

---

web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx
web/console/src/modules/registry/components/chart/ChartTablePanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): upgrade install helm sh

---

build/docker/tools/tke-installer/Dockerfile
build/docker/tools/tke-installer/run.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): entrypoint get args from user

---

cmd/tke-installer/app/installer/upgrader.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add ca crt for upgrade

---

cmd/tke-installer/app/installer/upgrader.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): upgrade depl whith input image

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): stop run local registry in upgrade

---

pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): only install nvidia device plugin on pgpu

---

.github/workflows/e2e.yml
.github/workflows/release.yml
build/docker/tools/provider-res/download.sh
build/docker/tools/tke-installer/release.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): docker pull with config

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): start registry failed

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): check installer mode from input

---

web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerItem.tsx
web/console/src/modules/common/models/Cluster.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): change check GPUManager method

---

pkg/platform/controller/addon/cronhpa/controller.go

/kind bug
The log here should be `Info`, not `Error`
Fixes #
NONE
None

fix(platform): fix loglevel for cronhpa

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/cluster/kubeadm_test.go
pkg/platform/provider/baremetal/cluster/update.go
pkg/platform/provider/baremetal/constants/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): change upgrade coredns logic

---

CHANGELOG/CHANGELOG-1.7.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add 1.7.1 changelog

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/cluster/kubeadm_test.go
pkg/platform/provider/baremetal/cluster/update.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): add need set coredns check

---

pkg/registry/chartmuseum/authorization/create_chart.go
pkg/registry/harbor/handler/proxy.go

label chart for filter query
Fixes #1499 
* Because kubernetes objects label key can't contain space, I replace space to `-`
* Compatible with registry and harbor
```release-note
```
```docs
```

feat(registry): label registry-chart with helm-chart keywords

---

docs/guide/zh-CN/QuickStart/快速入门.md
docs/guide/zh-CN/products/platform/cluster.md
hack/addon/readme/GPUManager.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: update gpu doc

---

README.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: update version to v1.8.0

---

README.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add tkestack upgrade link in readme

---

pkg/platform/provider/imported/validation/cluster.go

修改Imported类型的拼写错误
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): provider

---

.github/workflows/e2e.yml
pkg/spec/spec.go
test/e2e_installer/cluster/cluster_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): update support k8s versions

---

web/console/package-lock.json
web/console/package.json
web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/cluster/actions/validateClusterCreationAction.ts
web/console/src/modules/cluster/components/clusterManage/AsUserExtraInput.tsx
web/console/src/modules/cluster/components/clusterManage/CreateClusterPanel.tsx
web/console/src/modules/cluster/components/clusterManage/KubeconfigFileParse.tsx
web/console/src/modules/cluster/constants/initState.ts
web/console/src/modules/cluster/models/ClusterCreationState.ts

>
Fixes #
```release-note
```
```docs
```

feat(console):  add params for import cluster by kubeconfig

---

build/docker/tools/code-generator/Dockerfile
build/docker/tools/code-generator/Makefile

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): update code generator

---

cmd/tke-installer/installer.go
cmd/tke-platform-api/apiserver.go
cmd/tke-platform-controller/controller-manager.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/machine/provider.go
pkg/platform/provider/imported/cluster/provider.go
test/cmd/tke-up/main.go
test/e2e/platform/platform_test.go
test/tke/tke.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1657
```release-note
```
```docs
```

refactor(platform): add register provider func

---

api/platform/v1/types.go
cmd/tke-platform-controller/app/options/clustercontroller.go
cmd/tke-platform-controller/app/options/options.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/config/types.go
pkg/platform/controller/cluster/deletion/cluster_deleter.go

feat(platform): Random time for health check
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): Random time for health check

---

pkg/platform/provider/cluster/interface.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add k8s rest config provider

---

api/platform/types.go
api/platform/v1/types.go
pkg/application/util/helmclient.go
pkg/logagent/util/cluster.go
pkg/mesh/external/kubernetes/tke_clusters.go
pkg/monitor/util/cache/cache.go
pkg/platform/provider/cluster/interface.go
pkg/platform/registry/cluster/storage/tappcontroller.go
pkg/platform/types/types.go
pkg/platform/util/addon/client.go
pkg/platform/util/client.go
pkg/platform/util/credential/credential.go
pkg/platform/util/location.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): reduce util client builder

---

pkg/platform/provider/cluster/interface.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): cover nil credential case

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/types/types.go
pkg/platform/types/v1/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): installer restconfig always nil

---

pkg/monitor/util/cache/cache.go

>
> /kind bug
> /kind design
> /kind flake
Fixes
```release-note
```
```docs
```

fix(monitor): status locked may be nil

---

pkg/platform/provider/cluster/interface.go
pkg/platform/registry/cluster/storage/tappcontroller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): remove credential provider

---

pkg/platform/provider/cluster/interface.go
pkg/platform/provider/imported/validation/cluster.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(format): restconfig methods annotation

---

pkg/platform/provider/baremetal/cluster/delete.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/cluster/update.go
pkg/platform/provider/cluster/cluster.go
pkg/platform/provider/cluster/interface.go
pkg/platform/provider/imported/cluster/provider.go
pkg/platform/provider/imported/config/config.go
pkg/platform/registry/cluster/storage/tappcontroller.go
pkg/platform/util/client.go
pkg/platform/util/location.go
test/e2e/platform/platform_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): remove provider client input

---

pkg/platform/provider/cluster/cluster.go
pkg/platform/provider/cluster/interface.go
pkg/platform/registry/cluster/storage/tappcontroller.go
pkg/platform/util/client.go
pkg/platform/util/location.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): reduce provider method

---

api/platform/types.go
api/platform/v1/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): remove schema of host

---

pkg/platform/registry/cluster/storage/storage.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1688
```release-note
```
```docs
```

fix(platform): more info when get cluster

---

pkg/application/controller/app/action/install.go
pkg/application/controller/app/action/pull.go
pkg/application/controller/app/action/rollback.go
pkg/application/controller/app/action/types.go
pkg/application/controller/app/action/upgrade.go
pkg/application/controller/app/app_controller.go
pkg/application/provider/application/application.go
pkg/application/provider/application/interface.go
pkg/application/provider/example/application/application.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1682
```release-note
```
```docs
```

feat(platform): add application provider

---

api/platform/types.go
api/platform/v1/types.go
pkg/platform/registry/cluster/storage/proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): trim prefix in make url

---

pkg/platform/registry/cluster/storage/customresource_proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): trim prefix in build director

---

web/console/src/modules/cluster/components/clusterManage/SelectICComputerPanel.tsx
web/installer/src/modules/installer/components/EditingItem.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): enable edit username when add machine

---

pkg/platform/provider/baremetal/phases/containerd/containerd.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): support sudo with non-root user

---

web/console/helpers/urlUtil.ts

>
> /kind bug
fix: https://github.com/tkestack/tke/issues/1634
fix https://github.com/tkestack/tke/issues/1634 for release-1.8
Fixes #
```release-note
```
```docs
```

fix(console): when query value is empty ,url is wrong

---

CHANGELOG/CHANGELOG-1.8.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add change log 1.8.1

---

pkg/platform/proxy/core/pod/storage/exec.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support exec with impersonation

---

CHANGELOG/CHANGELOG-1.8.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add 1.8.1 change log

---

web/console/src/modules/uam/components/strategy/StrategyActionPanel.tsx

>
> /kind bug
由于开发者失误，写错了参数在object中的路径导致了代码死循环内存溢出，页面卡死
fix: 1716
Fixes #
```release-note
```
```docs
```

fix(console): create strategy endless loop

---

web/console/src/modules/uam/components/strategy/StrategyActionPanel.tsx

>
> /kind bug
fix: 1716
Fixes #
```release-note
```
```docs
```

fix(console):   create strategy endless loop for release-1.8

---

web/console/Wrapper.tsx
web/console/config/index.ts
web/console/config/platform.ts
web/console/index.project.tsx
web/console/index.tke.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceEventPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceLogPanel.tsx
web/console/src/modules/logStash/components/EditOriginContainerItemPanel.tsx
web/console/src/modules/project/components/user/list/UserTablePanel.tsx
web/console/src/modules/project/constants/Config.ts
web/console/webpack/webpack.dev.js

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): project page get undefined error

---

pkg/auth/util/user.go
pkg/business/registry/util/auth.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(busniss): admin checker for ldap case

---

api/platform/types.go
api/platform/v1/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): typo in platform types

---

pkg/application/controller/app/deletion/app_resources_deleter.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): more specific in not found case

---

pkg/gateway/api/api.go
pkg/gateway/api/platforminfo.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(gateway): add platform info api

---

web/console/src/webApi/cluster.ts
web/console/src/webApi/tkestack.ts

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): use platform info to get version

---

docs/design-proposals/installer-optimization.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: installer optimization

---

cmd/generate-images/main.go
cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1743
```release-note
```
```docs
```

feat(installer): push fewer imgs to local registry

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1744
```release-note
```
```docs
```

feat(installer): push images parallelly

---

pkg/platform/proxy/networking/ingress/storage/storage.go
pkg/platform/proxy/networking/rest/rest.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #1750 
```release-note
```
```docs
```

support ingress v1 api

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): deploy registry earlier

---

cmd/tke-platform-api/apiserver.go
cmd/tke-platform-controller/controller-manager.go
pkg/platform/provider/edge/cluster/provider.go
pkg/platform/provider/edge/conf/example/create_edge_cluster.yml

Signed-off-by: attleewang <attleewang@tencent.com>
/kind feature
fix(platform): add edge base cluster baremetal

fix(platform): add edge base cluster baremetal

---

cmd/tke-application-controller/app/application.go
cmd/tke-application-controller/app/config/config.go
cmd/tke-application-controller/app/context.go
cmd/tke-application-controller/app/options/feature.go
cmd/tke-application-controller/app/options/options.go
pkg/application/config/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(application): set syncPeriod and concurrentSyncs by config file

---

pkg/application/util/helmclient.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(application): get credential by clusterCredentialRef

---

pkg/application/controller/app/app_health.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): health check use informer get app

---

docs/design-proposals/lightweight.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add lightweight proposals

---

docs/design-proposals/add-ingress-gateway.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add ingress gate way

---

web/installer/.storybook/main.js
web/installer/package-lock.json
web/installer/package.json
web/installer/tsconfig.json
web/installer/webpack/webpack.dev.js
web/installer/webpack/webpack.prod.js

>
use open source tea-component, remove the third_party zip.
Fixes #
```release-note
```
```docs
```

feat(installer): rm third_party zip

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): set fewer chans for docker push

---

pkg/application/util/helmclient.go
pkg/platform/util/addon/client.go
pkg/platform/util/credential/credential.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): rm get cc form labelselector

---

pkg/util/apiclient/idempotency.go
pkg/util/apiclient/install.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat: create apiextensions-apiserver resource with file

---

pkg/application/registry/application/storage/rest.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): update app spec set status upgrading

---

docs/guide/zh-CN/best-practices/custom-k8s-version-upgrade.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: correct spelling mistakes of scheduler

---

docs/guide/zh-CN/best-practices/renewing-kubernetes-certificates.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add case for loopbackClient issue

---

cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/tke-auth/.helmignore
cmd/tke-installer/app/installer/manifests/charts/tke-auth/Chart.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-auth/templates/_helpers.tpl
cmd/tke-installer/app/installer/manifests/charts/tke-auth/templates/tke-auth-api.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-auth/templates/tke-auth-controller.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-auth/values.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/.helmignore
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/Chart.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/templates/_helpers.tpl
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/templates/tke-gateway.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/values.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-platform/.helmignore
cmd/tke-installer/app/installer/manifests/charts/tke-platform/Chart.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-platform/templates/_helpers.tpl
cmd/tke-installer/app/installer/manifests/charts/tke-platform/templates/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-platform/templates/tke-platform-controller.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-platform/values.yaml
pkg/application/helm/action/install.go
pkg/platform/types/v1/types.go

>
Fixes #
```release-note
```
```docs
```

feat(installer): install auth, platform, gateway through charts

---

pkg/apiserver/options/secure_serving.go

>
set 30 year for generate self-signed certificate
- https://github.com/kubernetes/kubernetes/issues/86552
Fixes #
```release-note
```
```docs
```

feat(platform): set 30 year for generate self-signed certificate

---

build/docker/tools/provider-res/download.sh

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): fix provider res docker config wrong place

---

cmd/tke-installer/app/installer/installer.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): helm uninstall chart after helm install chart wrong

---

pkg/gateway/gateway.go
pkg/gateway/websocket/handler.go
pkg/gateway/websocket/websocket.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(gateway): support proxy websocket request

---

pkg/platform/registry/cluster/storage/proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support proxy CR through websocket

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): support bridge in galaxy cni

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

Revert "fix(platform): support bridge in galaxy cni"

---

cmd/tke-installer/app/installer/upgrader.go
pkg/platform/provider/cluster/cluster.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): provider platform client nil when upgarde

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
Fixes #1802 
```release-note
```
```docs
```

fix(installer): failed to start docker daemon

---

build/docker/tools/tke-installer/install.sh

Revert "fix(installer): failed to start docker daemon"

---

charts/tke-platform/templates/tke-platform-api.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-platform/templates/tke-platform-api.yaml

>
> /kind bug
```release-note
```
```docs
```

fix(installer): update platform chart enable audit

---

CHANGELOG/CHANGELOG-1.9.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: update changelog 1.9.0

---

README.md

>
```release-note
```
```docs
```

docs: update readme.md 1.9.0 content

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/util/workqueue/metrics.go
pkg/platform/util/workqueue/priority_queue.go
pkg/platform/util/workqueue/rate_limiting_queue.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add priority queue for cluster_controller

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/machine/provider.go
pkg/platform/provider/edge/cluster/provider.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): remove EnsureDisableOffloading

---

api/platform/v1/cluster.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): import duplicate http package

---

pkg/logagent/util/cluster.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(logaget): correct proxy target url

---

cmd/tke-installer/app/installer/manifests/charts/tke-gateway/templates/tke-gateway.yaml
cmd/tke-installer/app/installer/manifests/tke-gateway/tke-gateway.yaml
hack/lightweight-install/tke-gateway/templates/tke-gateway.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1779
```release-note
```
```docs
```

fix(gateway): correct gateway service port

---

cmd/tke-installer/app/installer/manifests/charts/tke-registry/.helmignore
cmd/tke-installer/app/installer/manifests/charts/tke-registry/Chart.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/_helpers.tpl
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-api.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-controller.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/values.yaml

>
Fixes #
```release-note
```
```docs
```

feat(installer): add tke-registry chart file

---

pkg/logagent/controller/logagent/images/images.go

>
Fixes #
```release-note
```
```docs
```

refactor(installer): upgrade log-agent version to v1.2.0

---

cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/application_test.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-controller/tke-registry-controller.yaml
cmd/tke-installer/app/installer/types/types.go

>
Fixes #
```release-note
```
```docs
```

feat(installer): support platformApp install provisioner

---

cmd/tke-installer/app/installer/manifests/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-rbd/values.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/templates/deployment.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/templates/persistentvolumeclaim.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/templates/podsecuritypolicy.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/templates/role.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/templates/rolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/templates/serviceaccount.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/templates/storageclass.yaml
cmd/tke-installer/app/installer/manifests/charts/nfs-subdir-external-provisioner/values.yaml

>
Fixes #
```release-note
```
```docs
```

feat(installer): update nfs, ceph-rbd chart files

---

cmd/tke-installer/app/installer/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add ingres nginx image

---

cmd/tke-installer/app/installer/installer.go

>
Fixes #
```release-note
```
```docs
```

refactor(installer): skip audit install status check

---

web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx
web/console/src/modules/registry/components/chart/ChartTablePanel.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): correct helm push guide

---

web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx
web/console/src/modules/registry/components/chart/ChartTablePanel.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): correct helm pull guide

---

cmd/tke-installer/app/installer/manifests/charts/ceph-csi-rbd/templates/volumesnapshotclasses.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-rbd/templates/volumesnapshotcontents.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-rbd/templates/volumesnapshots.yaml

>
Fixes #
```release-note
```
```docs
```

refactor(installer): add ceph-csi-rbd volumesnapshot crd

---

cmd/tke-installer/app/installer/application.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): fix isntall ceph rbd provisioner

---

pkg/monitor/util/cache/cache.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(monitor): change query app failed log level

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): update registry api deployment replicas 1

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): stable images push with few worker

---

cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/influxdb/.helmignore
cmd/tke-installer/app/installer/manifests/charts/influxdb/Chart.yaml
cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/_helpers.tpl
cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-installer/app/installer/manifests/charts/influxdb/values.yaml

>
Fixes #
```release-note
```
```docs
```

feat(installer): install influxdb chart

---

cmd/tke-installer/app/installer/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add kube webhook image

---

pkg/platform/registry/cluster/storage/customresource_proxy.go

>
> /kind bug
> /kind design
> /kind flake
disable keepalive to avoid 502 and timeout
50000 request  5000 pre time
before 
now
Fixes #
```release-note
```
```docs
```

perf(custom-proxy): disable keepalive to avoid 502 and timeout

---

cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-controller.yaml

>
Fixes #
```release-note
```
```docs
```

refactor(installer): tke registry controller pod anti affinity

---

web/console/src/webApi/virtual-machine.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): create vm storageClass should use storageClassName

---

web/console/webpack/webpack.base.js

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): dayjs isMoment get error

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): update galaxy config

---

pkg/logagent/controller/logagent/images/images.go

>
Fixes #
```release-note
```
```docs
```

refactor(installer): upgrade log-file version to v1.2.0

---

web/console/src/modules/registry/components/apikey/ApiKeyTablePanel.tsx
web/console/src/modules/registry/components/repo/ImageTablePanel.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): correct image push guide

---

cmd/tke-auth-api/app/config/config.go
cmd/tke-auth-api/app/options/auth.go
go.mod
go.sum
pkg/apiserver/authentication/authenticator/oidc/oidc.go
pkg/auth/apiserver/apiserver.go
pkg/auth/authentication/oidc/claims/claims.go
pkg/auth/authentication/oidc/identityprovider/cloudindustry/cloudindustry.go
pkg/auth/authentication/oidc/identityprovider/cloudindustry/hook_cloudindustry.go
pkg/auth/registry/identityprovider/storage/storage.go
pkg/auth/util/dex/conn.go
pkg/auth/util/user.go
pkg/business/registry/portal/storage/storage.go
pkg/business/registry/util/auth.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

 feat(auth): support cloud industry oidc and accounts

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): disabel import charts

---

web/console/Wrapper.tsx
web/console/src/modules/cluster/components/clusterManage/ClusterActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerItem.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerNumPanel.tsx
web/console/src/modules/cluster/constants/Config.ts
web/console/src/modules/notify/components/resourceEdition/EditResourceChannel.tsx
web/console/src/modules/overview/components/ClusterOverview.tsx
web/console/src/modules/overview/components/OverviewApp.tsx
web/console/src/modules/registry/components/chart/list/ActionPanel.tsx
web/console/src/modules/registry/components/chartgroup/create/BaseInfoPanel.tsx
web/console/src/modules/uam/components/strategy/StrategyApp.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): hide some features

---

web/console/Wrapper.tsx
web/console/src/modules/application/components/app/ChartActionPanel.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): hide tkestack help and project item

---

cmd/tke-installer/app/installer/manifests/tke-audit-api/tke-audit-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(audit): use tke default service account

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/templates/tke-gateway.yaml
cmd/tke-installer/app/installer/manifests/tke-gateway/tke-gateway.yaml
pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(gateway): use node port instead

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(registry): registry dns support ha

---

cmd/tke-installer/app/installer/manifests/charts/ingress-nginx/templates/tke-ingress.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add tke ingress rules

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): move prepare pull images

---

cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/installer.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): industry code bug

---

build/docker/tools/tke-installer/dockerd-entrypoint.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add insecure registry

---

cmd/tke-installer/app/installer/manifests/charts/tke-gateway/templates/tke-gateway.yaml
cmd/tke-installer/app/installer/manifests/tke-gateway/tke-gateway.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): correct gateway manifest

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/templates/tke-gateway.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): stop uninstall gateway chart

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/tke-gateway/templates/tke-gateway.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): use node port type for gateway

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-upgrade/app/options/options.go
pkg/monitor/controller/prometheus/controller.go
pkg/monitor/controller/prometheus/yamls.go
pkg/monitor/storage/influxdb/metric/metric.go

support to collect vm metrics from libvirt level
Signed-off-by: willzgli <willzgli@tencent.com>
/kind feature

feat(monitor): support monitor kubevirt vms

---

test/util/cloudprovider/tencent/tencent.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(test): test e2e installer connect refused

---

pkg/application/controller/app/app_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): sync app status from helm release

---

pkg/application/controller/app/app_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): sync app status form helm release

---

pkg/application/controller/app/app_controller.go
pkg/application/registry/application/storage/rest.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): sync chart version in rollback

---

pkg/application/controller/app/app_controller.go
pkg/application/registry/application/storage/rest.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): sync chart version in rollback (#1908)

---

pkg/apiserver/filter/authentication.go
pkg/auth/authorization/local/authorizer.go
pkg/auth/filter/filter.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): authz deny bug fix

---

pkg/util/ssh/ssh.go
test/util/cloudprovider/tencent/tencent.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(test): ci test failed

---

pkg/monitor/services/rest/types.go

support edit vm alarmpolices

---

web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/action-panel.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/index.tsx
web/console/src/modules/common/hooks/useFetch.ts
web/console/src/webApi/virtual-machine.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): fix useFetch cant clear polling

---

.github/workflows/release-industry-cloud-1.9.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

ci: add release industry workflow

---

.github/workflows/release-industry-cloud-1.9.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

ci: echo branch name

---

web/console/config/routerConfig.ts
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceAdvancedPanel.tsx
web/console/src/modules/logStash/components/EditLogStashPanel.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console):  hide cronhpa

---

web/console/Wrapper.tsx
web/console/helpers/index.ts
web/console/helpers/isInIframe.ts
web/console/index.tke.tsx
web/console/public/index.html
web/console/public/webtty.html
web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx
web/console/src/modules/registry/components/apikey/ApiKeyTablePanel.tsx
web/console/src/modules/registry/components/repo/ImageTablePanel.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): change logo and support check is in iframe

---

cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/.helmignore
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/Chart.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/README.md
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/NOTES.txt
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/_helpers.tpl
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/ceph-conf.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/csiplugin-configmap.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-clusterrole.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-clusterrolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-http-service.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-role.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-rolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-serviceaccount.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-clusterrolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-http-service.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-psp.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-role.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-rolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-serviceaccount.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/secret.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/storageclass.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/values.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add ceph fs chart

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): update galaxy network conf

---

cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-api.yaml
cmd/tke-installer/app/installer/manifests/influxdb/influxdb.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
web/console/src/webApi/virtual-machine.ts

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): change accessmode to ReadWriteMany

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-installer/app/installer/manifests/charts/influxdb/values.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-api.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/values.yaml
cmd/tke-installer/app/installer/manifests/influxdb/influxdb.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add ceph fs option

---

cmd/tke-installer/app/installer/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): modify cephcsi version

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): prepull auth and paltform images

---

cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): transfor influxdb sts to depl

---

cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): remove servicename in deployment

---

cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/values.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): correct preprocess ceph fs values

---

cmd/tke-application-controller/controller-manager.go
pkg/application/controller/app/action/install.go
pkg/application/controller/app/action/rollback.go
pkg/application/controller/app/action/upgrade.go
pkg/application/controller/app/app_controller.go
pkg/util/metrics/util.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(application): add application metrics for failed

---

web/console/src/modules/vnc/index.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): keep page protocol with websocket protocol is same

---

web/console/src/modules/vnc/index.tsx

>
> /kind bug
之前修复ws和wss问题的时候，协议头多了一个冒号
Fixes #
```release-note
```
```docs
```

fix(console): rm extra colon for websocket 

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): fix check influxdb func

---

cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add cephfs pvc

---

cmd/tke-application-controller/controller-manager.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): use controller default port set metrics

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-upgrade/app/options/options.go

> /kind bug
enable influxdb service can be accessed from bussiness clusters by vip or third party lb

expose influxdb endpoint with vip

---

web/console/package-lock.json
web/console/package.json
web/console/src/modules/alarmPolicy/constants/Config.ts
web/console/src/modules/cluster/components/resource/virtual-machine/components/vmMonitorDialog.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/constants/index.tsx
web/console/src/modules/common/components/index.ts
web/console/src/modules/common/components/monitorPanel/constants.ts
web/console/src/modules/common/components/monitorPanel/index.tsx
web/console/src/webApi/monitor.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): support mutil drive 

---

web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/index.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): add bubble for Failure condition

---

web/console/src/modules/cluster/components/resource/virtual-machine/constants/index.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): vm_network_transmit_bw display mistake

---

build/docker/tools/tke-installer/install.sh

>
> /kind bug
Fixes #1802
```release-note
```
```docs
```

fix(installer): failed to start docker daemon (#1830)

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): set registry api deployment replicas to 2

---

web/console/package-lock.json
web/console/package.json
web/console/src/modules/common/components/clip/Clip.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): clip component maybe not working

---

web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(cosnole): when create ingress use apply

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): set registry api deployment replicas to 2 (#2007)

---

pkg/monitor/controller/prometheus/yamls.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(monitor): support monitor qgpu resources

---

pkg/platform/provider/baremetal/conf/containerd/config.toml
pkg/platform/provider/baremetal/conf/docker/daemon.json

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): change runtime cgdriver to systemd

---

api/platform/types.go
api/platform/v1/types.go
cmd/tke-platform-controller/app/options/clustercontroller.go
pkg/controller/config/client.go
pkg/controller/options/apiclient.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/config/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): controller support crd mode

---

pkg/util/ssh/ssh.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): ssh retry infinite loop

---

api/platform/types.go
api/platform/v1/types.go
pkg/platform/provider/baremetal/cluster/create.go

>
Fixes #
```release-note
```
```docs
```

feat(platform): update anywhere provider process

---

pkg/platform/provider/baremetal/phases/galaxy/galaxy.go
pkg/platform/provider/baremetal/phases/galaxy/images/images.go
pkg/platform/provider/baremetal/phases/galaxy/template.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add galaxy agent to gc

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/manifests.go
pkg/platform/provider/baremetal/constants/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): pre allocate svc ip for qgpu scheduler

---

pkg/platform/provider/baremetal/cluster/create.go

>
Fixes #
```release-note
```
```docs
```

feat(platform): update provider EnsureClusternetRegistration

---

pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): wait poll immediate cant support loop with err

---

web/console/helpers/reduceNetwork.ts
web/console/src/modules/audit/components/AuditSettingDialog.tsx
web/console/src/modules/cluster/actions/validatorActions.ts
web/console/src/modules/cluster/components/resource/nodeManage/UpdateNodeLabelDialog.tsx
web/console/src/modules/cluster/models/MonitorPanel.tsx
web/console/src/modules/notify/components/resourceEdition/EditResourceTemplate.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): gpu monitor unit display wrong and other bug

---

web/console/helpers/reduceNetwork.ts
web/console/src/modules/audit/components/AuditSettingDialog.tsx
web/console/src/modules/cluster/actions/validatorActions.ts
web/console/src/modules/cluster/components/resource/nodeManage/UpdateNodeLabelDialog.tsx
web/console/src/modules/cluster/models/MonitorPanel.tsx
web/console/src/modules/notify/components/resourceEdition/EditResourceTemplate.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): gpu monitor unit display wrong and another bug

---

pkg/platform/provider/baremetal/cluster/manifests.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): modify qgpu scheduler extender config

---

pkg/application/controller/app/action/install.go
pkg/application/controller/app/action/rollback.go
pkg/application/controller/app/action/upgrade.go
pkg/application/controller/app/app_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): restore metrics when app status is successed

---

api/platform/types.go
api/platform/v1/types.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/util/extenderapi/extenderapi.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): ensure app addons

---

cmd/tke-application-controller/app/options/options.go
pkg/application/controller/app/app_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): reconcile when deleted helm release (#2010)

---

web/console/src/modules/cluster/WebAPI/scale.ts
web/console/src/modules/cluster/components/scale/hpa/editor/hpa.tsx
web/console/src/modules/cluster/components/scale/hpa/list/namespaceSelect.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): create hpa back to list get wrong namesapce

---

cmd/tke-platform-controller/app/run.go
cmd/tke-platform-controller/app/webhook/validate.go

>
Fixes #
```release-note
```
```docs
```

feat(platform): support validate platform cluster

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/config/config.go
pkg/platform/provider/baremetal/machine/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): remove need set hosts

---

docs/guide/zh-CN/best-practices/renewing-kubernetes-certificates.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add kubelet case for renew crt

---

api/platform/v1/cluster.go
pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): provider not export real err

---

web/console/Wrapper.tsx
web/console/config/platform.ts
web/console/index.tke.tsx
web/console/lib/ff-redux/src/object/Action.ts
web/console/lib/ff-redux/src/object/Reducer.ts
web/console/package-lock.json
web/console/package.json
web/console/public/static/icon/data-service-hover.svg
web/console/public/static/icon/data-service.svg
web/console/src/modules/application/reducers/RootReducer.ts
web/console/src/modules/overview/reducers/RootReducer.ts
web/console/src/modules/project/reducers/RootReducer.ts
web/console/src/modules/registry/reducers/RootReducer.ts
web/console/tencent/paas-midleware/lib/index.js
web/console/tencent/paas-midleware/package.json
web/console/tencent/tea-app/package.json

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): tkeStack适配中间件

---

pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): register global cls failed

---

pkg/auth/filter/inspector.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): set cluster user as privileged user (#2066)

---

pkg/platform/controller/cluster/cluster_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): set cls to wrapper for no-crd mode

---

pkg/util/ssh/proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): ssh proxy dial target no time out

---

api/platform/types.go
api/platform/v1/types.go
pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/provider/baremetal/validation/machine.go
pkg/platform/provider/baremetal/validation/result.go
pkg/util/ssh/proxy.go
pkg/util/ssh/ssh.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add anywhere validate result

---

pkg/platform/provider/baremetal/validation/result.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): change vaildate rep json

---

pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): set cc is changed when modify it

---

build/docker/tools/job/Dockerfile

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add job docker file

---

pkg/application/controller/app/action/install.go
pkg/application/controller/app/action/list.go
pkg/application/controller/app/action/pull.go
pkg/application/controller/app/action/rollback.go
pkg/application/controller/app/action/uninstall.go
pkg/application/controller/app/action/upgrade.go
pkg/application/provider/application/interface.go
pkg/application/registry/application/storage/rest.go
pkg/application/registry/application/storage/rest_history.go
pkg/application/registry/application/storage/rest_resource.go
pkg/application/util/helmclient.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
/kind feature
Fixes #
```release-note
```
```docs
```

feat(application): get helm client with application provider restconfig

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/provider/baremetal/validation/constants.go
pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): validate firewall

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/manifests.go
pkg/platform/provider/baremetal/constants/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): remove qgpu config

---

pkg/platform/proxy/apps/daemonset/storage/pod.go
pkg/platform/proxy/apps/deployment/storage/pod.go
pkg/platform/proxy/apps/rest/rest.go
pkg/platform/proxy/apps/statefulset/storage/pod.go
pkg/platform/proxy/batch/job/storage/pod.go
pkg/platform/proxy/batch/rest/rest.go
pkg/util/page/continue.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support workload pods page

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/provider/baremetal/validation/constants.go
pkg/platform/provider/baremetal/validation/overridevalue.go
pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): validate storage info

---

pkg/platform/provider/baremetal/cluster/create.go

>
Fixes #
```release-note
```
```docs
```

feat(platform): update EnsureCluster to EnsureClusterAddressReal

---

cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/tke-platform/templates/cluster-info-configmap.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-platform/values.yaml
pkg/gateway/api/platforminfo.go

>
Fixes #
```release-note
```
```docs
```

feat(gateway): add tke namespace cluster-info comfigmap

---

build/docker/tools/job/Dockerfile

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add bash

---

pkg/platform/provider/baremetal/validation/cluster.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): validate storage info

---

pkg/logagent/controller/logagent/images/images.go

>
Fixes #
```release-note
```
```docs
```

refactor(installer): upgrade log-file version to v1.2.0 (#1875)

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): validate default route hangs

---

pkg/platform/proxy/apps/daemonset/storage/event.go
pkg/platform/proxy/apps/deployment/storage/event.go
pkg/platform/proxy/apps/statefulset/storage/event.go
pkg/platform/util/event.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

perf(platform): optimize query of events related to deployment

---

tools/clean.sh
web/console/src/modules/cluster/constants/Config.ts

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): add clean iptabel script

---

cmd/tke-auth-api/app/config/config.go
cmd/tke-auth-api/app/options/auth.go
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-api.yaml
cmd/tke-installer/app/installer/manifests/tke-application-api/tke-application-api.yaml
go.mod
go.sum
pkg/apiserver/authentication/authenticator/apikey/apikey.go
pkg/apiserver/authentication/authenticator/oidc/oidc.go
pkg/apiserver/filter/authentication.go
pkg/auth/apiserver/apiserver.go
pkg/auth/authentication/authenticator/apikey.go
pkg/auth/authentication/oidc/claims/claims.go
pkg/auth/authentication/oidc/identityprovider/cloudindustry/cloudindustry.go
pkg/auth/authentication/oidc/identityprovider/cloudindustry/hook_cloudindustry.go
pkg/auth/authorization/local/authorizer.go
pkg/auth/filter/filter.go
pkg/auth/registry/identityprovider/storage/storage.go
pkg/auth/util/dex/conn.go
pkg/auth/util/user.go
pkg/business/registry/portal/storage/storage.go
pkg/business/registry/util/auth.go
pkg/gateway/api/logout.go
pkg/gateway/auth/login.go
pkg/gateway/token/token.go
pkg/registry/apiserver/apiserver.go
pkg/registry/chartmuseum/authentication/authentication.go
pkg/registry/chartmuseum/chartmeseum.go
pkg/registry/distribution/auth/auth.go
pkg/registry/distribution/distribution.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(auth): cherry pick industry to master

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/edge/cluster/provider.go

>
Fixes #
```release-note
```
```docs
```

platform(refactor): add provider EnsureAuditConfig

---

pkg/util/extenderapi/extenderapi.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): cant get isnotfound error by gethelmrelease

---

pkg/platform/provider/baremetal/validation/cluster.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): precheck port 30086

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): update etcd to 3.4.13 and etcd config

---

web/console/src/modules/cluster/components/scale/hpa/editor/hpa.tsx
web/console/src/modules/cluster/components/scale/hpa/list/namespaceSelect.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): fix hpa list no default namespace

---

web/console/src/modules/cluster/components/clusterManage/InputLabelsPanel.tsx
web/console/src/modules/cluster/components/resource/nodeManage/CreateComputerPanel.tsx
web/console/src/modules/uam/components/group/list/RoleModifyDialog.tsx

> /kind bug
1. role list can't search;
2. create computer can't add label
Fixes #
```release-note
```
```docs
```

fix(console): create computer can't add label (for master)

---

web/console/src/modules/cluster/components/clusterManage/InputLabelsPanel.tsx
web/console/src/modules/cluster/components/resource/nodeManage/CreateComputerPanel.tsx
web/console/src/modules/uam/components/group/list/RoleModifyDialog.tsx

>
> /kind bug
1. role list can't search;
2. create computer can't add label
Fixes #
```release-note
```
```docs
```

fix(console): create computer can't add label

---

cmd/tke-installer/app/installer/manifests/charts/tke-auth/templates/tke-auth-api.yaml
cmd/tke-installer/app/installer/manifests/charts/tke-registry/templates/tke-registry-api.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add registry auth pod affinity

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/machine/kubeadm.go
pkg/util/apiclient/idempotency.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add default kubernetes topology zone lable (#2126)

---

pkg/util/ssh/ssh.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): ssh suport use env proxy

---

web/console/Wrapper.tsx

>
> /kind design
Fixes #
```release-note
```
```docs
```

feat(console): change menu theme to blue

---

web/console/src/modules/logStash/actions/namespaceActions.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): log table page auto select namespace - for master

---

web/console/src/modules/logStash/actions/namespaceActions.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): log table page auto select namespace

---

pkg/registry/distribution/notification/notification.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix tke-regisry push image questions 

---

web/console/package-lock.json
web/console/src/modules/alarmRecord/components/AlarmRecordPanel.tsx
web/console/src/modules/cluster/components/clusterManage/ConfigPromethus.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): add send status to alarm record table

---

pkg/platform/provider/baremetal/cluster/create.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): use domain for registry mirror

---

api/application/v1/generated.proto
api/application/v1/types.go
api/application/v1/types_swagger_doc_generated.go
api/openapi/zz_generated.openapi.go
pkg/application/registry/application/storage/storage.go
pkg/application/registry/application/storage/table.go

/kind feature
**What this PR does**:
Add `CHARTNAME`, `CHARTVERSION`, `STATUS` and `AGE` table when we get app, eg:
Fixes #2027

feat(application): update application table

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/util/ssh/os.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): fix nfs&ceph-fs validate connection timeout

---

web/console/src/modules/alarmRecord/components/AlarmRecordPanel.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): rm alarm status

---

web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerItem.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/registrySelect/index.ts
web/console/src/modules/cluster/components/resource/resourceEdition/registrySelect/registrySelectDialog.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/registrySelect/registryTagSelectDialog.tsx
web/console/src/modules/registry/components/repo/NamespaceDisplayNameEditor.tsx
web/console/src/modules/registry/components/repo/RepoTablePanel.tsx
web/console/src/webApi/index.ts
web/console/src/webApi/registry.ts

>
Fixes #
```release-note
```
```docs
```

feat(cosnole): when create workload add register dialog

---

web/console/Wrapper.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): add version to side menu

---

pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/phases/image/image.go

> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): support mirror config for worker

---

docs/user/tke-installer/normal-installation.md
pkg/platform/provider/baremetal/validation/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): update disk space

---

pkg/application/controller/app/app_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): update status causes sync release too fast

---

cmd/tke-installer/app/installer/manifests/tke-notify-api/tke-notify-api.yaml
cmd/tke-notify-api/app/config/config.go
cmd/tke-notify-api/app/options/feature.go
cmd/tke-notify-api/app/server.go
pkg/monitor/controller/prometheus/yamls.go
pkg/notify/apiserver/apiserver.go
pkg/notify/registry/rest/rest.go

1. fix bug in prometheus rule
2. add ttl for messagerequest
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(monitor): optimize monitor

---

api/platform/types.go
api/platform/v1/types.go
pkg/platform/controller/cluster/cluster_controller.go

Signed-off-by: danielxxli <danielxxli@tencent.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add new cluster phase waiting

---

pkg/platform/provider/baremetal/validation/cluster.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): validate cidr does not work

---

web/console/src/modules/common/components/clip/Clip.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): add copy tips to Clip component

---

web/console/package-lock.json
web/console/package.json
web/console/src/modules/common/components/clip/Clip.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): add tips for Clip component

---

web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNamespaceDetailPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceTablePanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/namespace-quota-manage/LimitRangePanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/namespace-quota-manage/ResourceQuotaConfig.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/namespace-quota-manage/ResourceQuotaPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/namespace-quota-manage/constants.ts
web/console/src/modules/cluster/components/resource/resourceTableOperation/namespace-quota-manage/index.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/namespace-quota-manage/utils.ts
web/console/src/webApi/namespace.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): add namespace quota management

---

cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/manifests/charts/tke-platform/templates/cluster-info-configmap.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add cluster info content

---

web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceTablePanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): resource table panel maybe blank

---

cmd/tke-installer/app/installer/manifests/charts/tke-platform/templates/cluster-info-configmap.yaml

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(platform): fix cluster-info cm generate failed

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/provider/baremetal/validation/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support skip validate item

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/provider/baremetal/validation/constants.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): split machine resource validate

---

pkg/platform/provider/baremetal/validation/cluster.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): remove old machine validate

---

pkg/auth/authentication/oidc/identityprovider/cloudindustry/cloudindustry.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support set iam app api endpoint

---

cmd/tke-installer/app/installer/manifests/tke-notify-api/tke-notify-api.yaml
pkg/notify/apiserver/handler.go
pkg/notify/controller/messagerequest/util/util.go

1. change alert time to local time
2. avoid using htlm escape charactors in message

feat(notify): optimize content of message

---

tools/clean.sh
web/console/src/modules/cluster/constants/Config.ts

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): update clean script

---

cmd/tke-application-controller/app/run.go
cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/installer.go
pkg/application/controller/app/action/install.go
pkg/application/controller/app/action/types.go
pkg/application/controller/app/action/upgrade.go
pkg/application/controller/app/app_controller.go
pkg/application/helm/action/install.go
pkg/application/helm/action/upgrade.go
pkg/application/registry/application/storage/rest.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): fix helm pending with context cancel

---

cmd/tke-application-controller/app/run.go
cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/installer.go
pkg/application/controller/app/action/install.go
pkg/application/controller/app/action/types.go
pkg/application/controller/app/action/upgrade.go
pkg/application/controller/app/app_controller.go
pkg/application/helm/action/install.go
pkg/application/helm/action/upgrade.go
pkg/application/registry/application/storage/rest.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): fix helm pending with context cancel.

---

web/console/helpers/request.ts
web/console/src/modules/application/WebAPI.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): change update application api to patch

---

cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/constants/constants.go
cmd/tke-installer/app/installer/images/images.go
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/.helmignore
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/Chart.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/README.md
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/NOTES.txt
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/_helpers.tpl
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/ceph-conf.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/csiplugin-configmap.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-clusterrole.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-clusterrolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-http-service.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-psp.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-role.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-rolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/nodeplugin-serviceaccount.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-clusterrolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-http-service.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-psp.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-role.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-rolebinding.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/provisioner-serviceaccount.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/secret.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/templates/storageclass.yaml
cmd/tke-installer/app/installer/manifests/charts/ceph-csi-cephfs/values.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): update cephcsi image

---

api/platform/cluster.go
api/platform/types.go
api/platform/v1/cluster.go
api/platform/v1/types.go
pkg/platform/provider/baremetal/validation/cluster.go
pkg/util/ssh/socks5_proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support socks5 proxy

---

web/console/src/modules/cluster/models/MonitorPanel.tsx

>
> /kind bug
修复了一些GPU指标显示不正确的问题
Fixes #
```release-note
```
```docs
```

fix(console): fix gpu monitor chart

---

web/console/tencent/tchart/src/tce/request.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): add csrf token to monitor chart request

---

web/console/src/modules/alarmRecord/components/AlarmTablePanel.tsx
web/console/src/modules/common/hooks/useFetch.ts
web/console/webpack/csrf.js

>
> /kind bug
1、在监控记录列表页面当continue token过期时添加跳转到第一页的提示
2、监控列表页面现在可以选择page size了
Fixes #
```release-note
```
```docs
```

feat(console): add continue token expired status

---

cmd/tke-installer/app/installer/manifests/charts/ingress-nginx/templates/tke-ingress.yaml

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): add ingress-nginx retry when master node reboot

---

web/console/src/modules/cluster/components/resource/virtual-machine/pages/detail/info/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/index.tsx

>
> /kind bug
vm status为running，但是ready为false，此时vm实际状态是异常的，新增Abnormal表示此状态
Fixes #
```release-note
```
```docs
```

fix(console): vm status is running but not ready

---

web/console/helpers/urlUtil.ts
web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx

>
> /kind bug
支持模糊搜索
Fixes #
```release-note
```
```docs
```

fix(console): support fuzzy search

---

pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): miss spell of selinux validation

---

api/registry/types.go
api/registry/v1/types.go
pkg/registry/apiserver/apiserver.go
pkg/registry/distribution/auth/auth.go
pkg/registry/distribution/auth/token.go
pkg/registry/distribution/client/repo.go
pkg/registry/distribution/handler/handler.go
pkg/registry/distribution/notification/notification.go
pkg/registry/registry/namespace/storage/storage.go
pkg/registry/registry/repository/storage/storage.go
pkg/registry/registry/rest/rest.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/2209
```release-note
```
```docs
```

fix(registry): support repush image

---

pkg/platform/provider/baremetal/cluster/kubeadm.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): miss node label

---

web/console/src/modules/cluster/components/resource/nodeManage/ComputerActionPanel.tsx
web/console/src/modules/cluster/components/resource/nodeManage/ComputerTablePanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNodeDetailPanel.tsx
web/console/tencent/paas-midleware/lib/index.js

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): sync data service api csrf token

---

web/console/src/modules/uam/components/group/create/BaseInfoPanel.tsx
web/console/src/modules/uam/components/group/list/RoleModifyDialog.tsx
web/console/src/modules/uam/components/user/create/UserCreate.tsx
web/console/src/modules/uam/components/user/list/RoleModifyDialog.tsx

>
Fixes #
```release-note
```
```docs
```

feat(console): rm tenant role

---

web/console/src/modules/cluster/components/resource/virtual-machine/constants/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/create/diskPanel.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/create/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/store/creation.ts
web/console/src/webApi/virtual-machine.ts

>
1、创建 vm 如果 sc的provisioner为rbd.csi.ceph.com，accessModes 设置为ReadWriteOnce
Fixes #
```release-note
```
```docs
```

feat(console): create vm support set accessModes by sc Provisioner

---

web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx

>
> /kind bug
> /kind design
> /kind flake
修复helm-push插件安装的提示。解压到$HOME/.local/share/helm/plugins修改为解压到$HOME/.local/share/helm/plugins/helm-push
Fixes #
```release-note
```
```docs
```

fix usage guider

---

web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceDetailPanel.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerLimitItem.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceActionPanel.tsx
web/console/src/modules/overview/components/ClusterDetailPanel.tsx
web/console/src/modules/overview/components/OverviewApp.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): 修复创建deployment时request memory含有小数的问题

---

build/docker/tools/tke-installer/dockerd-entrypoint.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add insecure-registry

---

web/console/tencent/paas-midleware/lib/index.js

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): delete-same-instance-issue

---

web/console/src/modules/cluster/components/resource/virtual-machine/pages/detail/event/index.tsx
web/console/src/webApi/virtual-machine.ts
web/console/webpack/webpack.dev.js

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): 新建vm新增blockMultiQueue和cache参数

---

test/e2e_installer/cluster/cluster_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): disable cluster upgrade test

---

test/e2e_installer/node/node_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(ci): import cluster provider

---

web/console/tencent/paas-midleware/lib/index.js

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): add medium option for backup

---

pkg/auth/web/templates/error.tmpl.html
web/console/src/modules/common/components/permission-provider/index.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): 修复判断是否可见缺少了children的问题

---

web/console/Wrapper.tsx
web/console/public/static/icon/data-service-hover.svg
web/console/public/static/icon/data-service.svg

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): 数据服务添加icon

---

build/docker/tools/tke-installer/release.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): retry upload installer

---

test/e2e_installer/node/node_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(ci): copy provider config in test

---

pkg/application/controller/app/action/uninstall.go
pkg/application/controller/app/deletion/app_resources_deleter.go
pkg/application/helm/action/install.go
pkg/application/helm/action/upgrade.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): app install/upgrade failed when release pending

---

pkg/platform/provider/baremetal/validation/machine.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): check firewall for machine

---

pkg/platform/provider/baremetal/phases/image/image.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): ignore registry cert

---

pkg/application/helm/action/install.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): fix install app error

---

pkg/util/x509/parse.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): judge where decode is nil before ParseCertificate

---

pkg/platform/registry/cluster/storage/storage.go
pkg/platform/registry/cluster/strategy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): cluster status is Terminating, update will delete it

---

pkg/application/registry/application/storage/storage.go
pkg/platform/registry/cluster/storage/storage.go
pkg/platform/registry/clustercredential/storage/storage.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): watch cluster/clustercredential/application with options

---

SECURITY.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(security): add security contributor section

---

pkg/platform/proxy/apps/deployment/storage/replicasets.go
pkg/platform/util/replicasets.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): support replicasets sort by version

---

pkg/platform/registry/cluster/storage/storage.go
pkg/platform/registry/clustercredential/storage/storage.go
pkg/platform/registry/cronhpa/storage/storage.go
pkg/platform/registry/csioperator/storage/storage.go
pkg/platform/registry/machine/storage/storage.go
pkg/platform/registry/persistentevent/storage/storage.go
pkg/platform/registry/tappcontroller/storage/storage.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): resource watch and deletecollection validate tencentid
