tkestack/tke

pkg/notify/registry/template/storage/storage.go
pkg/notify/registry/template/strategy.go

Tke list function will always filtered by TenantID, but PredicateFunc and AttrFunc not set in the template module which lead to an empty result.

fix:notify template list filtered by TenantID always get empty result

---

cmd/tke-installer/app/installer/manifests/etcd/etcd.yaml

fix: etcd use headless service, instead of using cluster IP with LB

---

pkg/platform/proxy/apps/deployment/storage/event.go
pkg/platform/util/client.go

Fixes #50 
This PR fixes:
- Requested events of the deployment and its replicaSets and pods in parallel.
- Filtered events from the resources of different deployments with the same labels.

Optimized listing deployment events

---

pkg/util/ssh/ssh.go

What happened:  
The original code tries to run `sha256sum` on the remote machine before copy, but the file to be checked in `.sha256` file is wrong, which means the check always fail
fixes #126

check dst file sha256sum before ssh copy

---

cmd/tke-auth-api/app/config/config.go
cmd/tke-auth-api/app/options/auth.go
cmd/tke-auth-api/app/server.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml
cmd/tke-installer/app/installer/manifests/tke-gateway/tke-gateway.yaml
docs/devel/running-locally.md
pkg/auth/apiserver/apiserver.go
pkg/auth/authorization/aggregation/aggregation.go
pkg/auth/authorization/local/authorizer.go

1. Fix tke-gateway proxy tke-auth-api wrong name #134 
2. Fix create the same admin user if pods for tke-auth-api started at the same time

Fix gateway auth-api proxy config and create admin user conflict

---

pkg/platform/controller/addon/ipam/images/images.go
pkg/platform/controller/addon/ipam/ipam_controller.go
pkg/platform/provider/baremetal/phases/galaxy/images/images.go
pkg/platform/provider/baremetal/phases/galaxy/template.go

- Support for dynamic network config. Load unknown network config from /etc/cni/net.d/ to co-work with other cni plugins. This makes ENI network co-work with the default global vpc route network on qcloud.
- IPAM supports allocating floatingip to TApp/replicasets pods.
- Fix IPAM corner cases resulting of unreleased ips.

Upgrade galaxy/ipam to v1.0.1

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

ref: https://github.com/tkestack/galaxy/pull/30

fix: add node name env for galaxy daemonsets

---

Makefile
build/lib/common.mk
build/lib/create-manifest.sh
build/lib/image.mk

1. Only ask users to enable the experimental features of Docker when `cross-building` docker images.
2. Check Docker API version instead of Docker version.

fix: Only ask users to enable experimental features when necessary

---

pkg/platform/provider/baremetal/phases/galaxy/template.go

without this arg, flannel will auto-detect host ip as outside encapsulation
packet's source ip. If there're muilt-ips in host net interface and the `first` ip is
not what we need, network may fail.

fix: add --iface=$(HOST_IP) arg in flannel

---

cmd/tke-platform-controller/app/options/clustercontroller.go
cmd/tke-platform-controller/app/options/machinecontroller.go
cmd/tke-platform-controller/app/options/options.go

the following parameters added in commit 4df559f6b11e33e255adc649f85877030f01ad4e are read from config file but not set to `options`:
* `controller.machine_sync_period`
* `controller.concurrent_machine_syncs`
* `controller.cluster_sync_period`
* `controller.concurrent_cluster_syncs`

fix machine & cluster controller parameters not read

---

cmd/tke-platform-controller/app/options/feature.go
pkg/monitor/storage/thanos/metric/metric.go

fix: get rid of empty samples of metric query for thanos backend

---

pkg/registry/util/request/request.go
pkg/util/http/request.go

the function `DomainFromRequest` is supposed to extract tenantID from request host, such as `default` from `default.registry.com`, but `SplitHostPort` in `DomainFromRequest` reports error if there is no `:port` in `req.Host`, which makes the function `TenantID` always return the `defaultTenant`

fix tenant not read from registry domain

---

cmd/tke-installer/app/installer/installer.go

Allow to install global on the machine running tke-installer, need add `EnsureDocker` into `cluster.spec.features.skipConditions`.

feat: allow to install global on the machine running tke-installer

---

cmd/tke-installer/app/installer/installer.go

create cluster need more time to validate spec.

fix: extend imporResource timeout

---

pkg/platform/controller/addon/ipam/images/images.go
pkg/platform/controller/addon/ipam/ipam_controller.go
pkg/platform/provider/baremetal/cluster/manifests.go
pkg/platform/provider/baremetal/phases/galaxy/images/images.go

update galaxy image version
galaxy ipam use clusterIP service to avoid nodePort issue in some ipvs scenario

feat:update galaxy version and change galaxy-ipam service as clusterIP

---

pkg/platform/proxy/apps/deployment/storage/storage.go

fix: the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1)

fix(cluster): rollback does not match the expected API version

---

cmd/tke-audit-api/app/config/config.go
cmd/tke-auth-api/app/config/config.go
cmd/tke-business-api/app/config/config.go
cmd/tke-gateway/app/config/config.go
cmd/tke-installer/app/app.go
cmd/tke-installer/app/run.go
cmd/tke-logagent-api/app/config/config.go
cmd/tke-monitor-api/app/config/config.go
cmd/tke-notify-api/app/config/config.go
cmd/tke-platform-api/app/config/config.go
cmd/tke-registry-api/app/config/config.go

close http debug path host:port/debug/pprof;
in tke-install pprof  is installed in default http mux
while tke-xx-api pprof is installed by apiserver restful mux

feat: Disable http debug url (#284)

---

pkg/platform/controller/addon/ipam/ipam_controller.go

galaxy-ipam use ClusterIP service type in [#271]( https://github.com/tkestack/tke/pull/271)
There is bug that its service still use NodePort field.

fix(galaxy-ipam): fix galaxy-ipam service

---

pkg/util/ssh/ssh.go

due to https://github.com/golang/crypto/commit/0a08dada0ff98d02f3864a23ae8d27cb8fba5303#diff-aab72d98d6b840106cb1ffed0390f951

fix: ssh with private key

---

docs/devel/running-locally.md

With a certificate generated by `mkcert`, which is PKCS#8 formatted, we will get error:
```
Error: unable to decode private key PEM: unable to get PrivateKey from PEM type: PRIVATE KEY
```
Should we do necessary conversion silently or just improve the documentation?

docs: explanation for tokenPrivateKeyFile format

---

pkg/platform/provider/baremetal/cluster/provider.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(cluster): adjust SkipConditions priority

---

pkg/platform/controller/addon/prometheus/yamls.go

/kind bug
metric k8s_node_status_ready now group_left with kube_node_labels, which comes from each node. We cannot get kube_node_labels if a node is down, cause no data of k8s_node_status_ready for this node. Alarm depending on k8s_node_status_ready will fail.
Fixes #
```release-note
NONE
```
```docs
```

fix(platform): update metric k8s_node_status_ready

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/util/log/context.go

/kind bug
Try to fix the panic when deleting cluster.
Some defensive codes are added to `log.FromContext` to avoid the same mistakes that call `log.FromContext` without setting the logger.
Fixes #
```release-note
NONE
```
```docs
```

fix: FromContext panic

---

pkg/platform/controller/addon/ipam/ipam_controller.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/manifests.go
pkg/platform/provider/baremetal/constants/constants.go

/kind bug
backport from 1.3, try to fix:
1. kube-scheduler can not access galaxy-ipam by service name, change to service ip, and allocate service ip for ipam.
2. create an empty configmap for floating ip, otherwise ipam can not work.
Fixes #
```release-note
```
```docs
```

fix(cluster): backport from 1.3 to fix ipam service ip and floating ip cm

---

web/console/Wrapper.tsx
web/console/config/resource/common/apiVersion.ts
web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
web/console/src/modules/cluster/actions/clusterActions.ts
web/console/src/modules/cluster/actions/resourcePodLogActions.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodLogPanel.tsx
web/console/src/modules/logStash/WebAPI.ts
web/console/src/modules/logStash/actions/clusterActions.ts
web/console/src/modules/logStash/components/EditLogStashPanel.tsx
web/console/src/modules/logStash/components/EditOriginContainerItemPanel.tsx
web/console/src/modules/logStash/components/EditOriginContainerPanel.tsx
web/console/src/modules/logStash/components/LogStashActionPanel.tsx

1. Fix the checking of logHierarchy call response.
2. Trim clusterId from namespace when checking if the logStash rule name exists.
3. Disable multiple namespace selection of new logStash rule on the service side.
4. Refine the checking of if the logging add-on exists.
5. Add watching of logAgent module

fix(console): disable multiple namespace selection

---

web/console/src/modules/cluster/actions/validateClusterCreationAction.ts
web/console/src/modules/cluster/components/clusterManage/CreateClusterPanel.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): create Import cluster address split error

---

pkg/controller/server.go
pkg/monitor/storage/project/metrics.go

/kind bug
In former commit (1b8a822e8660cbbacf14e5956c2166e14c64e3f9) tke-monitor-controller uses k8s.io/component-base/metrics/legacyregistry instead of github.com/prometheus/client_golang/prometheus/promhttp to provide metrics.
This causes other metrics like rate_limiter_use of all controllers fail to expose.
Fixes #
```release-note
NONE
```
```docs
```

fix(monitor): use prometheus client instead of k8s legacyregistry

---

cmd/tke-notify-api/app/server.go

/kind bug
notifyAddress stored in tke-notify-api configmap is wrong
Fixes #
```release-note
NONE
```
```docs
```

fix(notify): fix wrong notifyAddress stored in tke-notify-api cm

---

pkg/monitor/controller/prometheus/controller.go
pkg/platform/controller/addon/prometheus/controller.go

/kind bug
apiversion of CustomResourceDefinition change from apiextensionsv1beta1 to apiextensionsv1 at 1.17, add backward compatibility logic to prometheus addon
Fixes #
```release-note
NONE
```
```docs
```

fix(promethues): fix that deploy prometheus on k8s before 1.17 fails

---

pkg/platform/controller/addon/prometheus/metrics.go

> /kind bug
code setting labels of prometheus_status_fail using wrong names
Fixes #
```release-note
NONE
```
```docs
```

fix(prometheus): fix wrong label name of metric prometheus_status_fail

---

pkg/platform/controller/addon/ipam/ipam_controller.go

/kind bug
Cannot create `ipam` service with nodePort, remove nodePort, backport from release-1.3
Fixes #
NONE
```release-note
```
```docs
```

fix(cluster): remove ipam service nodePort

---

pkg/util/docker/docker.go
pkg/util/docker/docker_test.go

> /kind bug
> Fix the problem of parsing docker images.
> Before fixing: installer cannot parse image name like `localhost:5000/library/test-amd64:v1.2.3` correctly
N/A
Add test cases.
```release-note
```
```docs
```

fix(installer): use standard function to parse docker image name

---

pkg/platform/controller/addon/cronhpa/controller.go
pkg/platform/controller/cluster/deletion/cluster_deleter.go

/kind bug
Delete `CronHPA` addon when deleting cluster.
Fixes #
```release-note
```
```docs
```

fix(cluster): remove CronHPA when deleting cluster

---

pkg/monitor/controller/prometheus/metrics.go

> /kind bug
metric adding in commit ef0b6698acabac52c1779ecb8fe2d32f247d5118 causes conflict between prometheus controlled by monitor and platform. As prometheus switch to monitor is working in progress, change the name for now until the transition is complete.
Fixes #
```release-note
NONE
```
```docs
```

fix(monitor): fix metric conflict in monitor prometheus controller

---

pkg/platform/provider/baremetal/machine/kubeadm.go

/kind bug
Should use advertise address when kubeadm join node.
Fixes #
```release-note
```
```docs
```

fix(cluster): use advertise address when kubeadm join node

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/images/images.go
pkg/platform/provider/baremetal/manifests/metrics-server/metrics-server.yaml

Deploy metrics server for new clusters, providing metrics for other functions like HPA.
Fixes #
```release-note
add metrics-server to cluster feature
```
```docs
```

feat(platform): add metrics-server to cluster feature

---

pkg/platform/types/types.go

Revert "fix(cluster): query credentials and be compatible with older clusters"

---

api/platform/cluster.go
pkg/platform/types/v1/types.go
pkg/platform/util/client.go

> /kind bug
1) 5s client timeout is too small for certain busy cluster
2) When cluster address.path is set, it should be add to host url after host:port pair
Fixes #
```release-note
```
```docs
```

Platform fix

---

pkg/monitor/controller/prometheus/controller.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/util/apiclient/version.go

> /kind bug
k8s 1.16 deprecates apiextensions.k8s.io/v1beta1,  use apiextensions.k8s.io/v1 instead
Fixes #
```release-note
```
```docs
```

fix(prometheus): fix k8s 1.16 cannot install prometheus

---

pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

/kind bug
Support to compare kubelet versions with pre-release version.
Fixes #
```release-note
```
```docs
```

fix(cluster): update kubelet version compare

---

cmd/generate-images/main.go

Support generating image list for archs spefified by command line arg `--archs`, with this feature we can generate smaller tarball.

feat(installer): generate image list for specified archs

---

web/console/package-lock.json
web/console/package.json
web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceRollbackDialog.tsx
web/console/src/modules/common/models/CreateResource.ts

/kind bug
when cluster version >= 1.14, deployment rollback fail
this pull request backend fix at there [https://github.com/tkestack/tke/pull/670](https://github.com/tkestack/tke/pull/670)
Fixes #
```release-note
```
```docs
```

fix(console): add sluster version compare in deployment rollback request

---

pkg/util/apiclient/install.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(cluster): yaml split error

---

docs/design-proposals/api-trunking-combination-query-support.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(docs): add limitaion to api trunking

---

pkg/gateway/proxy/handler/rewriteproxy/handler.go
pkg/gateway/proxy/proxy.go

/kind feature
This PR makes it's possible to overview component openapi through tke-gateway.
Available components:
- platform(/tke-platform-api)
- business(/tke-business-api)
- notify(/tke-notify-api)
- monitor(/tke-monitor-api)
- auth(/tke-auth-api)
- registry(/tke-registry-api)
- logagent(/tke-logagent-api)
Fixes #
```release-note
```
```docs
```

feat(gateway): support component openapi overview

---

CONTRIBUTING.md
README.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs(contributing.md): add contributing document

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/machine/provider.go

fix https://github.com/tkestack/tke/issues/634
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): access nodeport cause 63s delay

---

pkg/platform/provider/baremetal/manifests/metrics-server/metrics-server.yaml

> /kind bug
metrics-server relies on certs on master node, add node affinity to bind it to master node
Fixes #688
```release-note
```
```docs
```

fix(platform): add nodeAffinity to bind metrics-server to master

---

pkg/platform/provider/baremetal/manifests/metrics-server/metrics-server.yaml

> /kind bug
add master node toleration for metrics-server
Fixes #
```release-note
```
```docs
```

fix(platform): add master toleration for metrics-server

---

docs/design-proposals/hostname-as-nodename-support.md

/kind design
Proposal of hostname as nodename support.
Fixes #
```release-note
```
```docs
```

docs(platform): hostname as nodename support

---

pkg/monitor/controller/prometheus/yamls.go
pkg/platform/controller/addon/prometheus/yamls.go

> /kind bug
add missing labels for kubelet metrics
fix scheduler latency metric for 1.18
add k8s_node_not_ready
Fixes #
```release-note
```
```docs
```

fix(platform,monitor): add missing labels for kubelet metrics 

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/machine/machine_controller.go

/kind feature
This PR is part of stage 2 work of https://github.com/tkestack/tke/blob/master/docs/design-proposals/hostname-as-nodename-support.md.
Fixes #
```release-note
```
```docs
```

feat(platform): add machineIP to old nodes

---

hack/auth/policy.json

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

build(policy.json): add action of createpodexec to viewer

---

cmd/tke-installer/app/installer/installer.go
pkg/util/apiclient/idempotency.go

/kind bug
fix missing sysctl.conf
Fixes #
```release-note
```
```docs
```

fix(installer): miss sysctl.conf

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/types/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): skip docker login when no username

---

pkg/monitor/storage/thanos/metric/metric.go

> /kind bug
set thanos query timeout to 60s, 10s is too small
Fixes #
```release-note
```
```docs
```

fix(monitor): set thanos query timeout to 60s

---

.github/workflows/release.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

ci(install): highlight build status

---

web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx
web/console/src/modules/cluster/components/resource/resourceTableOperation/UpdateWorkloadRegistryPanel.tsx
web/console/src/modules/cluster/models/MonitorPanel.tsx
web/console/src/modules/overview/components/ClusterOverview.tsx
web/installer/src/modules/installer/components/Step9.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): fix project meterice request header error

---

web/console/src/modules/cluster/models/MonitorPanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console):  monitor chart ready status display error

---

api/platform/v1/cluster.go
cmd/tke-installer/app/installer/installer.go
docs/guide/zh-CN/installation/installation-procedures.md
docs/guide/zh-CN/products/platform/cluster.md
web/installer/src/modules/installer/components/Step2.tsx

/kind bug
Using NodePort as auth server will make HA not really work.
VIP + NodePort will resolve this issue.
Fixes #
```release-note
```
```docs
```

fix(auth): HA not work for auth webhook

---

api/platform/v1/types.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/phases/galaxy/galaxy.go
pkg/platform/provider/baremetal/phases/galaxy/template.go

Currently flannel backend type is hardcoded in tke source as `vxlan` , this PR enables passing `vxlan` or `host-gw` through ClusterSpec.NetworkType field.

feat(platform): support customize flannel backend type

---

pkg/gateway/proxy/proxy.go
pkg/monitor/controller/prometheus/controller.go

/kind bug
Send alert to correct webhook addr through tke-gateway in non-global cluster.
Fixes #758
```release-note
```
```docs
```

fix(monitor): send alert to correct webhook addr

---

pkg/platform/provider/baremetal/validation/cluster.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): fix empty pointer

---

pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

/kind bug
If node join cluster through `kubeadm join`, InitConfiguration and clusterConfiguration is not in the host. Adding `--config` flag will case `no InitConfiguration or ClusterConfiguration kind was found in the YAML file` error.
If `--config` is not set, kubeadm will get InitConfiguration and clusterConfiguration from configmap when renew certs.
Fixes #
```release-note
```
```docs
```

fix(platform): remove flag when renew certs

---

pkg/gateway/proxy/proxy.go

Signed-off-by: Liu Hua <weldonliu@tencent.com>
>
/kind bug
> /kind design
> /kind flake
Without this patch, tke-gateway will panic when no notify component registerd.
Fixes #
```release-note
```
```docs
```

fix(gateway): fix null-pointer panic when no notify registered

---

build/docker/tke-gateway/build.sh
web/console/index.tsx
web/console/package.json
web/installer/package.json

>
> /kind bug
1、add set -e in build/docker/tke-gateway/build.sh;
2、add -q in package.json unzip, hide unused logs.
https://github.com/tkestack/tke/issues/788
Fixes #
```release-note
```
```docs
```

ci(console): fix console part build faild, but ci not exit

---

web/console/src/modules/cluster/components/KubectlDialog.tsx
web/console/src/modules/common/models/Cluster.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): kubeconfig api server path display error

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/machine/kubeadm.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/745
Fixes  https://github.com/tkestack/tke/issues/770
```release-note
```
```docs
```

fix(platform): allow user specify node name for cloud provider case

---

build/lib/create-manifest.sh

> /kind bug
> /kind design
`arm64/unknown` is only for UOS. 
We should use `arm64/v8` when pushing arm64 images to docker hub
Fixes #835

fix(builder): push arm64/v8 to docker hub

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/deletion/cluster_deleter.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
fix https://github.com/tkestack/tke/issues/792
```release-note
```
```docs
```

fix(platform): set owner reference leverage GC delete object

---

web/console/src/modules/logStash/components/EditLogStashPanel.tsx

>
/kind bug
> /kind design
> /kind flake
Links to cluster creation of log-stash are error.
Fixes #
```release-note
```
```docs
```

fix(console): logstash link path fixed

---

pkg/monitor/controller/prometheus/controller.go
pkg/platform/controller/addon/prometheus/controller.go

> /kind bug
Now that for failed prometheus, controller checks status for serveral minutes and give up; It should be checking forever until prometheus recovers.
Fixes #
```release-note
```
```docs
```

fix(platform,monitor): check prometheus status until it recovers

---

pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/cluster/update.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go

/kind bug
When ssh connection is not stable (for example when machine has just reboot), `EnsureAPIServerCert` may remove `apiserver.crt` and can not recover it by retry.
Fixes #
NONE
```release-note
```
```docs
```

fix(cluster): lost apiserver cert

---

pkg/monitor/controller/prometheus/controller.go
pkg/platform/controller/addon/prometheus/controller.go
pkg/platform/provider/baremetal/manifests/metrics-server/metrics-server.yaml

instead of run on master node for metrics-server and prometheus
adapter
We run mertics-server and prometheus-adapter on master since they need front-proxy-ca.crt, this ca file is stored in extension-apiserver-authentication configmap which we can use instead of master hostpath
Fixes #
```release-note
```
```docs
```

fix(platform,monitor): use extension-apiserver-authentication cm

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/types/types.go

After introducing infinite retry, ClusterProgress.Status should be marked as 'retrying', otherwise response of /api/cluster/global/progress will be confusing

fix(installer): mark status as retrying rather failed when a step failed

---

pkg/platform/provider/baremetal/preflight/checks.go

/kind bug
This PR improved the port checking. The former implement without `-n` may miss some port, because `ss` will show port's name instead of number. The `-w` arg for `grep` tries to figure out different ports with the same prefix like `:80` and `:8080`.
Fixes #
```release-note
```
```docs
```

fix(cluster): check port

---

web/console/src/modules/alarmPolicy/constants/Config.ts
web/console/src/modules/cluster/components/clusterManage/ClusterUpdate.tsx

>
1、node type alarm add memoru used item;
2、cluster update add rule only can upgrade version great one.
Fixes #
```release-note
```
```docs
```

feat(console): add alarm node memory used

---

web/console/src/webApi/cluster.ts

>
> /kind bug
when cluster version is empty, cluster list load fail
Fixes #
```release-note
```
```docs
```

fix(console): add cluster version is empty case

---

build/docker/tools/tke-installer/init_installer.sh
build/docker/tools/tke-installer/install.sh
cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/types/types.go
cmd/tke-installer/app/installer/upgrader.go
cmd/tke-installer/app/options/options.go
pkg/registry/apis/config/v1/types.go
pkg/spec/spec.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat(installer): support upgrade through installer

---

pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): set gpu-manager and gpu-quota-admission log to stderr

---

web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx
web/console/src/modules/cluster/components/clusterManage/ClusterUpdate.tsx
web/console/src/modules/cluster/components/clusterManage/WorkerUpdate.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/webApi/cluster.ts

>
> /kind bug
1. pod query can input any pod name;
2.master upgrade page ,when use manual mode ,hide max pod unready item;
3. when has worker upgrading, cluster list show loading icon  and look workers link
Fixes #
```release-note
```
```docs
```

fix(console): 1.5.0-alpha bug fix 2020-12-02

---

web/console/src/modules/cluster/actions/resourcePodActions.ts
web/console/src/modules/cluster/actions/validateWorkloadActions.ts
web/console/src/modules/cluster/components/resource/resourceDetail/ResourceGrayUpgradeDialog.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodActionPanel.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodPanel.tsx
web/console/src/modules/cluster/models/ResourceDetailState.ts
web/console/src/modules/cluster/reducers/ResourceDetailReducer.ts

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): support bypercentage for tapp gray update

---

pkg/platform/registry/cluster/strategy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): allow global to be the cluster name

---

pkg/monitor/controller/prometheus/yamls.go
pkg/platform/controller/addon/prometheus/yamls.go

> /kind bug
fix gpu-manager metrics not scraped
Fixes #998
```release-note
```
```docs
```

fix(platform,monitor): fix gpu-manager metrics not scraped

---

pkg/platform/provider/baremetal/images/images.go

Co-authored-by: 罗小仁 <xrluo@alauda.io>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): one node with multi gpu cause gpu-manager crash (#981)

---

pkg/application/registry/application/strategy.go
pkg/application/registry/application/validation.go
pkg/application/registry/application/validation_test.go

>
> /kind bug
same spec.name(helm chart release name) app can not in different cluster.
Fixes #1041
@jianzzz I didn't modify the tenantID as we discussed yesterday because I learned that the cluster belongs to a tenantID, so the tenantID is irrelevant. Before I thought the cluster can correspond to multiple tenantIDs. 
The search scene is compatible with my modified conditions and more flexible. 👍
NONE
For more information on release notes see: …

fix(application): same release name app can in different cluster

---

api/platform/validation/cluster.go
api/platform/validation/machine.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): skip validate spec.machines on update cluster

---

web/console/helpers/downloadCrt.ts

>
> /kind bug
https://github.com/tkestack/tke/issues/1074
Fixes #
```release-note
```
```docs
```

fix(console): remove "context" from  kubeconfig name

---

cmd/tke-business-api/app/config/config.go
cmd/tke-platform-api/app/config/config.go
pkg/apiserver/util/signals.go
pkg/auth/filter/inspector.go
pkg/registry/util/coredns.go
pkg/util/apiclient/client.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #1076
```release-note
```
```docs
```

fix(auth,platform): add authorization of rbac in inspectors

---

pkg/apiserver/authentication/config.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(apiserver): remove basic auth

---

test/tke/installer.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: handle install retrying status

---

pkg/monitor/controller/prometheus/controller.go
pkg/platform/controller/addon/prometheus/controller.go

> /kind bug
set replica of alertmanager to 1 to avoid cluster split
Fixes #
```release-note
```
```docs
```

fix(platform,monitor): set replica of alertmanager to 1

---

web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): open cluster monitor get error

---

web/console/helpers/downloadCrt.ts

Revert "fix(console): remove "context" from  kubeconfig name"

---

web/console/src/modules/notify/components/resourceEdition/EditResource.tsx

>
> /kind bug
at create notify channel page , when input bulr, value will loose.
Fixes #
```release-note
```
```docs
```

fix(console): fix when blur input value will loose

---

pkg/apiserver/filter/authentication.go
pkg/apiserver/openapi/openapi.go
pkg/platform/apiserver/apiserver.go
pkg/platform/proxy/version/rest/rest.go

fix https://github.com/tkestack/tke/issues/1134
Fixes #
```release-note
```
```docs
```

feat(platform): proxy cluster version api

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/machine/create.go
pkg/platform/provider/baremetal/machine/provider.go

This reverts commit 60ea9c21c064c5a5830a60eadefe478c8329f946.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Revert "Remove EnsureDisableOffloading"

---

pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
pkg/platform/provider/baremetal/phases/kubeadm/kubeadm_test.go

/kind bug
v1.20.4 should be same with 1.20.4
Fixes #
```release-note
```
```docs
```

fix(platform): remove v in same version comparing

---

web/console/src/modules/cluster/WebAPI/ClusterAPI.ts

…istency with the backend
kind bug
This PR rewritten clustercredential into abbreviated form cc to keep the  cluster credential naming style  maintain consistency which baremetal cluster created and imported cluster created.
Fixes #1164
```release-note
NONE
```

fix(webconsole): rewritten clustercredential into abbreviated

---

web/console/helpers/downloadCrt.ts
web/console/helpers/version.ts
web/console/src/modules/cluster/components/clusterManage/ClusterUpdate.tsx
web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodPanel.tsx
web/console/src/webApi/cluster.ts

>
> /kind bug
1、fix 1.20.4 can't upgrade to 1.20.4-tke.1
2、fix when not have cacert, display undefined in kubeconfig
3、fix pod running duration display wrong
https://github.com/tkestack/tke/issues/1168
https://github.com/tkestack/tke/issues/1173
Fixes #
```release-note
```
```docs
```

fix(console): k8s version updgrade and kubeconfig wrong

---

test/tke/tke.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(release, test): create cluster failed

---

pkg/monitor/controller/prometheus/yamls.go

/kind bug
Two kubelet metrics name have been changed since v1.19. TKE uses the previous name in monitor-controller which will make pod metrics alarming malfunctioning.
see here:
https://github.com/kubernetes/kubernetes/pull/92407
Fixes #1184 
NONE

fix(monitor-controller):  kubelet metrics name changed

---

pkg/platform/proxy/client.go
pkg/platform/registry/cluster/storage/proxy.go
pkg/platform/registry/cluster/storage/storage.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix: invalid token and host for ProxyRest

---

docs/design-proposals/cilium.md
docs/yamls/cilium/clusterCilium.yaml
docs/yamls/cilium/clusterCilium0.yaml
docs/yamls/cilium/installCilium.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs(design-proposal): support CNI Cilium

---

pkg/platform/proxy/networking/ingress/storage/event.go
pkg/platform/proxy/networking/ingress/storage/storage.go
pkg/platform/proxy/networking/rest/rest.go

(cherry picked from commit b9070b08ee6bf80ff93939bfc53493258f41333e)
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): networking v1beta1 do NOT support status and event

---

pkg/platform/provider/baremetal/cluster/provider.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): remove cilium enabled by default

---

cmd/tke-installer/app/installer/manifests/thanos/thanos.yaml
docs/design-proposals/installer-thanos-support.md

/kind bug
Fixes #
```release-note
```
```docs
```

fix(docs,installer): limit thanos-receive-nodeport svc port to expose

---

cmd/tke-installer/app/installer/types/types.go

>
/kind bug
Monitor elasticsearch backend should allow to use an empty username and password.
Fixes #1344 
```release-note
```
```docs
```

fix(installer): allow use empty username and password for es

---

pkg/monitor/controller/prometheus/yamls.go

>
/kind bug
node_ready metrics chart in node monitoring is malfunctioning currently due to a lack of `node_role` label in `k8s_node_status_ready`. This pr will fix it by add node_role label to `k8s_node_status_ready`.
QL use in chart:
```sql
SELECT max(value) AS k8s_node_status_ready FROM global.autogen.k8s_node_status_ready WHERE node_role = 'Node' AND time >= '2021-06-10 05:58:52' AND time < '2021-06-10 06:58:52' GROUP BY time(1m), node
```
record in influxdb(before pr):
time        |        __name__        |         cluster_display_name   |  cluster_id | node    |   prometheus    | …

fix(monitor): add node_role label for k8s_node_status_ready

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-upgrade/app/options/options.go

>
/kind bug
Currently a []byte type password will be fed to the configmap template, which will cause issue. Convert it to a string fix it.
Fixes #1084 
This pr fix the issue, however, I don't think use the trick(encoding/json treats []byte as b64 encoded) to do a base64 decoding and hide it from the coder is a good thing. Maybe use a string type like audi-api is a better way?
```release-note
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, …

fix(monitor): convert elastic password bytes to string

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/kubeadm.go

>
/kind bug
1. update `EnsurePatchAnnotation` to a safe way to patch annotation, now we don't need to check the kubeadm's version.
2. update to use secure-port for kube-scheduler and kube-controller-manager
3. set `bind-address` of kube-scheduler and kube-controller-manager to `0.0.0.0` by default. Then prometheus could scrape metrics through host IP.
Fixes #1353 
tested on 1.20.4-tke.1, 1.19.7, 1.18.3, 1.17.13, 
NONE
```release-note
```
**Additional documentation e.g., KEPs …

fix(platform): fix metrics for kube-scheduler

---

pkg/notify/controller/messagerequest/smtp/send.go

/kind bug
Currently the code use port as a flag to check whether tls has been enabled in mail channel while there is an real tls flag exists in channel configuration. This pr will shifting from using port to using the tls field in channel configuration.
Fixes #1384 
```release-note
```
```docs
```

fix(notify): fix tls condition in mail channel

---

test/tke/tke.go

Sometimes the importing cluster case in e2e test failed without tke problem, 
so we retry more times to import cluster in e2e test.

fix(test): retry ImportCluster more times

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/deletion/cluster_deleter.go
pkg/platform/controller/machine/deletion/machine_deleter.go
pkg/platform/controller/machine/machine_controller.go
pkg/platform/provider/baremetal/cluster/delete.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/machine/delete.go
pkg/platform/provider/baremetal/machine/provider.go

> /kind bug
Fix tke can't delete machine when delete its cluster.
1. Modify cluster/machine needsUpdate check;
2. Move delete cluster/machine to provider;
3. Fix some log error;
4. Fix patch machine finalizer context。
Fixes #1351

fix(platform): delete machine failed & move machine operation to provider

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
cmd/tke-installer/app/installer/manifests/tke-registry-controller/tke-registry-controller.yaml
cmd/tke-installer/app/installer/types/types.go

/kind bug
Add s3 storage option for registry. Now users can choose to use s3 as distribution's backend in intaller's configuration.
Fixes #1437
If a user choose s3 as registry backend, currently only docker images will be saved in the choosing storage as charts are stored in etcd by default. 
NONE
```release-note
```
```docs
```

fix(installer, registry): add s3 storage backend for registry

---

pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/provider/baremetal/conf/config.yaml
pkg/platform/provider/baremetal/validation/cluster.go
test/e2e/manifests/tke-platform-api/tke-platform-api.yaml
test/e2e/platform/platform_test.go
test/e2e/tke/tke.go

add namespace in kube config
> /kind bug
Without this pr:
1.  platfomClient  in tke-platform-controller will be nil
2. tke-platform-api pod will resolve tke-platformapi service with pod ip ranther than service ip
3. validating can not skip  checking spec.version with global cluster

fix(platform): test e2e failed

---

pkg/platform/provider/baremetal/phases/galaxy/galaxy.go
pkg/platform/provider/baremetal/phases/galaxy/template.go

/kind bug
Currently flannel does not set iface to the parameter set in cluster configuration.
Fixes #1441 
NONE
NONE

fix(platform): fix flannel iface

---

hack/addon/readme/CSIOperator.md
pkg/platform/controller/addon/storage/csioperator/controller.go

> /kind bug
CSI-Operator need storage controller and sidecar images in local docker registry.
Fixes #1414 
1. Need push this images to docker hub:
```sh
cephfsplugin:v0.3.0
cephfsplugin:v1.0.0
csi-attacher:v0.4.2
csi-provisioner:v0.4.2
csi-resizer:v0.5.0
csi-snapshotter:v0.4.1
csi-tencentcloud-cbs:v0.2.1
csi-tencentcloud-cbs:v1.2.0
driver-registrar:v0.3.0
livenessprobe:v0.4.1
rbdplugin:v0.3.0
rbdplugin:v1.0.0
```
2. **NOTE:** Stack now use a old version csi-operator image (ID sha256:b77952b83730), which only looks like v1.0.2. 
Version of driver in this image is v1.0.0 but [the version in csi-operator code is …

fix(platform): add csi-operator sidecar and controller images

---

pkg/platform/controller/machine/machine_controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1366
ref: https://github.com/tkestack/tke/blob/master/docs/design-proposals/hostname-as-nodename-support.md
```release-note
```
```docs
```

fix(platform): rm ensure mc label

---

cmd/tke-installer/app/installer/installer.go

> /kind bug
Add console ip to global cluster apiServer SAN.
Fixes #1307

fix(platform): add console ip to global apiServer SAN(#1307)

---

Makefile

> /kind bug
Fixes #1416 
The addon descriptions  orignal files is under `hack/addon/readme`.
Once we update or add files there, we need to excute `make asset` to generate some [assets code](https://github.com/tkestack/tke/tree/master/pkg/platform/registry/clusteraddontype/assets) with those static rescoures.

fix(platform): upgrade addon description

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/cluster_controller_test.go
pkg/platform/controller/machine/machine_controller.go
pkg/platform/controller/machine/machine_controller_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): update cls/mc needupdate logic

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/machine/machine_controller.go
pkg/platform/provider/cluster/interface.go
pkg/platform/provider/machine/interface.go

User can define  customized `needUpdate` function in provider, default reture false.
Fixes #1484

fix(platform): add needUpdate func in cluster/machine provider

---

Makefile

> /kind bug
Daily_build actions execute `make release.build`, 
but this command doesn't `make asset` by default, so I add `make asset`
If `NEED_BUILD_PROVIDER==true` or PR actions, we will make asset in #1421
Fixes #1416
```release-note
```
```docs
```

fix(Makefile): release lack of asset

---

web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterDetailBasicInfoPanel.tsx
web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterPlugInfoPanel.tsx
web/console/src/modules/common/models/Cluster.ts

>
Fixes #
fix: https://github.com/tkestack/tke/issues/1536
```release-note
```
```docs
```

feat(console): when cluster is containerd, disabled open logagent

---

web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterDetailBasicInfoPanel.tsx
web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterPlugInfoPanel.tsx
web/console/src/modules/common/models/Cluster.ts

>
pr: https://github.com/tkestack/tke/pull/1549 使用了错误的字段`spec.features.enableContainerRuntime`来判断集群的运行时组件, 现修改为`spec.features.containerRuntime`
Fixes #
```release-note
```
```docs
```

fix(console): should use spec.features.containerRuntime

---

api/openapi/zz_generated.openapi.go
api/platform/types.go
api/platform/v1/defaults.go
api/platform/v1/generated.proto
api/platform/v1/types.go
api/platform/v1/zz_generated.defaults.go
cmd/tke-installer/app/installer/installer.go
test/tke/tke.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): set container runtime as required

---

pkg/platform/provider/baremetal/constants/constants.go
pkg/platform/provider/baremetal/preflight/checks.go
pkg/util/ssh/interface.go
pkg/util/ssh/ssh.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): check cni config file

---

cmd/tke-installer/app/installer/upgrader.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): upgrade gateway in installer

---

pkg/platform/provider/baremetal/images/images.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): add pause for kubeadm job

---

pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): add checkpoint data file for gpumanager

---

web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx
web/console/src/modules/registry/components/chart/ChartTablePanel.tsx

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): upgrade install helm sh

---

pkg/platform/provider/baremetal/manifests/cilium/cilium.yaml
pkg/platform/provider/baremetal/manifests/cilium/eni-ipamd.yaml
pkg/platform/provider/baremetal/manifests/cilium/masq-agent.yaml
pkg/platform/provider/baremetal/manifests/cilium/router.yaml

> /kind bug
currently the request and limit resources weren't set in the manifests of the cilium workloads. this pull request is target to solve the issue.
Fixes #1312

fix(installer): add request and limit resources for cilium workload

---

pkg/app/app.go

>
/kind bug
> /kind design
> /kind flake
bug fix
Fixes #
NONE
```release-note
```
```docs
```

fix(platform): currect the wrong name passed to helpCommand()

---

api/platform/types.go
api/platform/v1/types.go
pkg/logagent/util/cluster.go
pkg/platform/proxy/core/pod/storage/log.go
pkg/platform/types/types.go
pkg/platform/util/client.go
pkg/platform/util/rest/stream.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1663
```release-note
```
```docs
```

fix(platform): log failed for user impersonation

---

web/console/config/resource/common/apiVersion.ts
web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
web/console/src/modules/common/webapi/PromethusAPI.ts

>
> /kind bug
1、关闭prometheuses时，之前使用了prometheuses对象上的selfLInk属性，由于selfLInk属性废弃，导致请求失败，现在改用name属性拼接
2、之前会同时请求platform前缀的prometheuses列表和monitor前缀的prometheuses列表，并且合并两者结果，现在修改了resourceInfo,彻底删除platform前缀的请求
Fixes #
```release-note
```
```docs
```

fix(console): update prometheuses resourceinfo

---

api/platform/types.go
api/platform/v1/types.go
cmd/tke-installer/app/installer/installer.go
pkg/application/util/helmclient.go
pkg/logagent/util/cluster.go
pkg/mesh/external/kubernetes/tke_clusters.go
pkg/monitor/util/cache/cache.go
pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/cluster/cluster.go
pkg/platform/provider/cluster/interface.go
pkg/platform/provider/imported/validation/cluster.go
pkg/platform/proxy/client.go
pkg/platform/registry/cluster/storage/tappcontroller.go
pkg/platform/types/types.go
pkg/platform/types/v1/types.go
pkg/platform/util/addon/client.go
pkg/platform/util/client.go
pkg/platform/util/location.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): impl restconfig provider

---

pkg/monitor/util/cache/cache.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(monitor): dynamic clientset is nil

---

pkg/monitor/util/cache/cache.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(monitor): cluster dynamic client is nil

---

pkg/platform/provider/cluster/interface.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(installer): client is nil in preparation

---

cmd/tke-platform-api/app/config/config.go
cmd/tke-platform-api/app/options/feature.go
cmd/tke-platform-api/app/options/options.go
cmd/tke-platform-api/app/server.go
pkg/platform/apiserver/apiserver.go
pkg/platform/registry/cluster/storage/customresource_proxy.go

支持url与集群中的crd请求连接相同，直接访问到集群的crd资源
>
> /kind bug
> /kind design
> /kind flake
支持通过正常http请求访问集群中crd资源。无需经过一下转发接口
```
/apis/platform.tkestack.io/v1/clusters/clusterName/proxy?path=
```
Fixes #
```release-note
```
```docs
```

feat(platform): add not found proxy

---

pkg/platform/registry/cluster/storage/cronhpa.go
pkg/platform/registry/cluster/storage/csioperator.go
pkg/platform/registry/cluster/storage/tappcontroller.go
pkg/platform/util/client.go
pkg/platform/util/location.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): reduce apiserver locaion input

---

pkg/platform/registry/cluster/storage/customresource_proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): trim prefix in not found proxy

---

pkg/platform/controller/cluster/cluster_controller.go
pkg/platform/controller/cluster/cluster_controller_test.go
pkg/platform/controller/machine/machine_controller.go
pkg/platform/controller/machine/machine_controller_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1703
```release-note
```
```docs
```

fix(platform): healcheck resync internal not work

---

pkg/auth/registry/apikey/storage/storage.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1716
```release-note
```
```docs
```

fix(auth): delete user is blocked in controller

---

.github/workflows/release.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

ci: trigger release every three days

---

cmd/tke-application-controller/app/run.go

give a customized name to controller  leader's lock resource
in active-backup mode. It's already been implemented in platform
controller.
>
/kind feature
give a customized name to  application controller  lock resource.  To be consistent 
with platorm controller.

optimize application controller lock name

---

pkg/platform/registry/cluster/storage/proxy.go
pkg/platform/registry/cluster/storage/proxy_test.go

/kind bug
1. Exracting and valiating host and port by spliting string with
keys is not reasonable. The original way will return a fake
error with a valid host like http://192.168.1.11:8080/abc
2. request dose not support insert header with impersonation informations
Fixes #
```release-note
```
```docs
```

fix bug in impersonation request

---

cmd/tke-installer/app/installer/manifests/tke-audit-api/tke-audit-api.yaml
docs/guide/zh-CN/QuickStart/快速入门.md
docs/guide/zh-CN/best-practices/jenkins.md
docs/guide/zh-CN/best-practices/offline-pot/roles/base-component/templates/elk/filebeat-k8s.yaml.j2
docs/guide/zh-CN/products/platform/cluster.md
pkg/monitor/controller/prometheus/controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/1756
```release-note
```
```docs
```

fix: stop using rbac v1beta1

---

api/application/types.go
api/application/v1/types.go
pkg/application/controller/app/action/pull.go
pkg/application/controller/app/app_controller.go

fix(application): rm app phase chart fetched

---

pkg/platform/registry/cluster/storage/proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): don't set user in header when proxy

---

charts/values/customConfig.yaml
charts/values/generateChartValues.go
charts/values/main.go
charts/values/struct.go

>
generate auth, platform, gateway chart custom values
Fixes #
```release-note
```
```docs
```

build(installer): generate auth, platform, gateway chart custom values

---

pkg/platform/controller/machine/machine_controller.go
pkg/platform/controller/machine/machine_controller_test.go
pkg/platform/provider/machine/interface.go

Signed-off-by: malc0lm <malclee@outlook.com>
/kind feature
The health checking use machine IP which acquired in tenant cluster node IP in machine controller. But in some scenario like [SuperEdge](https://github.com/superedge/superedge), we use the node name to get the node. So machine health checking always failed. 
In fact, health checking in provider need support user level implementation, this pr add `OnHealthCheck` in machine provider, and mv the origin default implementation in DelegateProvider.
Fixes #
```release-note
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), …

feat(platform): machine provider support OnHealthCheck interface

---

charts/values/generateChartValues.go

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(installer): generate admin password value wrongly

---

pkg/platform/apiserver/apiserver.go
pkg/platform/apiserver/install.go
pkg/platform/proxy/client.go

>
> /kind bug
> /kind design
> /kind flake
tke-platform-api support "autoscaling v2beta2" rest api
Fixes #
```release-note
```
```docs
```

feat(platform): support autoscaling v2beta2

---

web/console/package-lock.json
web/console/package.json
web/console/src/modules/cluster/components/resource/virtual-machine/pages/create/diskPanel.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/create/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/store/creation.ts
web/console/src/modules/cluster/constants/Config.ts
web/console/src/modules/vnc/constants.ts
web/console/src/modules/vnc/index.tsx
web/console/src/modules/vnc/vncClipboard.tsx
web/console/webpack/webpack.dev.js

>
Fixes #
```release-note
```
```docs
```

feat(console): support paste string to vnc

---

cmd/tke-installer/app/config/config.go
cmd/tke-installer/app/installer/application.go
cmd/tke-installer/app/installer/application_test.go
cmd/tke-installer/app/installer/installer.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): support install platform apps

---

web/console/src/modules/registry/components/apikey/ApiKeyTablePanel.tsx

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(console): update images related guide

---

api/client/clientset/internalversion/typed/platform/internalversion/platform_client.go
api/client/clientset/versioned/typed/platform/v1/platform_client.go
pkg/platform/provider/cluster/interface.go
pkg/platform/types/types.go
pkg/platform/types/v1/types.go

>
> /kind bug
> /kind design
> /kind flake
Set default qps form 5 to unlimited. default qps is too small for high frequency requests, which makes timeout if concurrent requests greater than 5
`Fixes #<issue 1846>`
Fixes #
```release-note
```
```docs
```

feat(platform): set default client qps unlimit if qps is not set

---

web/console/webpack/webpack.base.js

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix(console): dayjs isMoment get error for industry-cloud-1.9

---

pkg/logagent/registry/logagent/storage/fileproxy.go
pkg/logagent/util/logagent.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

rfactor(logagent): update log file port

---

pkg/monitor/services/rest/types.go
pkg/notify/apiserver/handler.go

1. fix alert rule expression for vm
2. add vm name in alert message
3. round values in prometheus alert annotation to two decimals
Signed-off-by: willzgli <willzgli@tencent.com>
> /kind bug

fix(monitor): support configure vm alert rule

---

web/console/src/modules/alarmPolicy/WebAPI.ts
web/console/src/modules/alarmPolicy/actions/alarmPolicyActions.ts
web/console/src/modules/alarmPolicy/actions/namespaceActions.ts
web/console/src/modules/alarmPolicy/components/AlarmPolicyTablePanel.tsx
web/console/src/modules/alarmPolicy/components/EditAlarmPolicyObject.tsx
web/console/src/modules/alarmPolicy/components/EditAlarmPolicyPanel.tsx
web/console/src/modules/alarmPolicy/components/EditAlarmPolicyVM.tsx
web/console/src/modules/alarmPolicy/constants/Config.ts
web/console/src/modules/cluster/components/resource/virtual-machine/components/index.ts
web/console/src/modules/cluster/components/resource/virtual-machine/components/vmMonitorDialog.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/constants/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/action-panel.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/index.tsx
web/console/src/modules/notify/actions/resourceActions.ts
web/console/src/modules/notify/schema/templateSchema.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): support virtual monitor and alarm

---

web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/action-panel.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/index.tsx
web/console/src/modules/common/hooks/useFetch.ts
web/console/src/modules/logStash/actions/logActions.ts
web/console/src/modules/logStash/components/EditLogStashPanel.tsx
web/console/src/modules/logStash/components/LogStashTablePanel.tsx
web/console/src/modules/logStash/constants/Config.ts
web/console/src/webApi/virtual-machine.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): change create vm network mode to virtio

---

pkg/logagent/controller/logagent/logagent_controller.go

add-mountpropagation-config
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(logagent): add propagation config

---

.github/workflows/release-industry-cloud-1.9.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

ci: use specific branch

---

pkg/platform/proxy/extensions/ingress/storage/event.go
pkg/platform/proxy/storage/storageclass/storage/event.go
pkg/util/apiclient/version.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support ingress and storage event for v1 version

---

pkg/platform/proxy/networking/ingress/storage/event.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): support networking ingress event for v1 version

---

api/platform/types.go
api/platform/v1/types.go
pkg/platform/provider/baremetal/cluster/create.go
pkg/platform/provider/baremetal/cluster/provider.go
pkg/platform/types/v1/types.go

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/tkestack/tke/issues/2004
```release-note
```
```docs
```

feat(platform): support registry to cluster net

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/provider/baremetal/validation/constants.go
pkg/util/ssh/proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

refactor(platform): set less info when check proxy

---

go.mod
go.sum
pkg/auth/authentication/oidc/identityprovider/cloudindustry/cloudindustry.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(cloudindustry): support searchKey and limit

---

cmd/tke-platform-controller/app/webhook/validate.go
pkg/platform/provider/baremetal/validation/cluster.go
pkg/platform/provider/baremetal/validation/constants.go
pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add validates for anywhere cluster

---

pkg/platform/provider/baremetal/validation/cluster.go
pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): validate storage addr failed

---

tools/clean.sh
web/console/src/modules/cluster/constants/Config.ts

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(console): add clean iptabel script

---

pkg/platform/provider/baremetal/cluster/create.go

…ollImmediate conditionFunc
>
Fixes #
```release-note
```
```docs
```

refactor(platform): update provider check helmrelease conditionFunc

---

pkg/application/controller/app/action/install.go
pkg/application/controller/app/action/upgrade.go
pkg/application/helm/action/install.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): update install failed and upgrade failed message

---

tools/clean.sh
web/console/src/modules/cluster/constants/Config.ts

>
Fixes #
```release-note
```
```docs
```

feat(console): add clean 9100 port

---

cmd/tke-installer/app/installer/installer.go
cmd/tke-installer/app/installer/manifests/charts/influxdb/templates/influxdb.yaml
cmd/tke-upgrade/app/options/options.go
pkg/monitor/apis/config/helpers_test.go

expose influxdb svc as nodeport in non-ha mode  global cluster and ha mode global cluster. it will unify the remote writing address for promethues in global cluster and business cluster.
Signed-off-by: willzgli <willzgli@tencent.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement …

fix(monitor): expose influxdb svc as nodeport

---

pkg/application/helm/action/install.go

Signed-off-by: DanielXLee <lixin8611@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(application): create target namespace when install application

---

pkg/platform/provider/baremetal/cluster/kubeadm.go
pkg/platform/provider/baremetal/machine/kubeadm.go
pkg/util/apiclient/idempotency.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add default kubernetes topology zone label

---

web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerItem.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/registrySelect/index.ts
web/console/src/modules/cluster/components/resource/resourceEdition/registrySelect/registrySelectDialog.tsx
web/console/src/modules/cluster/components/resource/resourceEdition/registrySelect/registryTagSelectDialog.tsx
web/console/src/modules/registry/components/repo/NamespaceDisplayNameEditor.tsx
web/console/src/modules/registry/components/repo/RepoTablePanel.tsx
web/console/src/webApi/index.ts
web/console/src/webApi/registry.ts

>
Fixes #
```release-note
```
```docs
```

feat(cosnole): when create workload add register dialog - for master

---

web/console/src/modules/alarmPolicy/actions/validatorActions.ts

>
> /kind bug
Fixes #
```release-note
```
```docs
```

fix:  alarm vm_cpu_usage_rate can over 100

---

pkg/auth/filter/filter.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(auth): add second auth check

---

pkg/platform/proxy/core/node/storage/pod.go
pkg/platform/proxy/core/node/storage/storage.go
pkg/platform/proxy/core/rest/rest.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(platform): add pagination for node/pods

---

pkg/util/ssh/socks5_proxy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): validate socks5 proxy

---

hack/etcdbackuper/Chart.yaml
hack/etcdbackuper/README.md
hack/etcdbackuper/templates/clusterrole.yaml
hack/etcdbackuper/templates/clusterrolebinding.yaml
hack/etcdbackuper/templates/deployment.yaml
hack/etcdbackuper/templates/namespace.yaml
hack/etcdbackuper/templates/persistenceVolumeClaim.yaml
hack/etcdbackuper/templates/secret-etcd-certs.yaml
hack/etcdbackuper/templates/serviceAccount.yaml
hack/etcdbackuper/values.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(installer): add etcdbackuper

---

web/console/src/modules/cluster/components/resource/virtual-machine/pages/detail/info/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/list/index.tsx

>
> /kind bug
vm status为running，但是ready为false，此时vm实际状态是异常的，新增Abnormal表示此状态
Fixes #
```release-note
```
```docs
```

fix(console): vm status is running but not ready

---

pkg/util/ssh/os.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): fix selinux validation

---

pkg/platform/proxy/apps/daemonset/storage/pod.go
pkg/platform/proxy/apps/deployment/storage/pod.go
pkg/platform/proxy/apps/statefulset/storage/pod.go
pkg/platform/proxy/batch/job/storage/pod.go
pkg/platform/proxy/core/node/storage/pod.go
pkg/platform/util/pod.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(platform): sort workload pods for page

---

web/console/src/modules/cluster/components/resource/virtual-machine/constants/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/create/diskPanel.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/pages/create/index.tsx
web/console/src/modules/cluster/components/resource/virtual-machine/store/creation.ts
web/console/src/webApi/virtual-machine.ts

>
1、创建 vm 如果 sc的provisioner为rbd.csi.ceph.com，accessModes 设置为ReadWriteOnce
Fixes #
```release-note
```
```docs
```

feat(console): create vm support set accessModes by sc Provisioner

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
Install ingress for global failed, because of unmarshaling rawValues failed for no alignment
Fixes #
```release-note
NONE
```
```docs
```

fix(installer): fix ingress chart raw values yaml no alignment

---

cmd/tke-installer/app/installer/installer.go

>
> /kind bug
install global cluster failed
Fixes #
```release-note
NONE
```
```docs
```

fix(installer): check influxdb chart condition failed

---

web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx

>
> /kind bug
修复Chart上传指引中，helm push插件安装位置指引的问题。
Fixes #
```release-note
```
```docs
```

fix(console): correct the path of helm push plugin

---

pkg/logagent/controller/logagent/logagent_controller.go

>
> /kind bug
The logagent has enabled hostNetwork, and the DNS policy is Clusterfirst. During domain name resolution, the pod inherits the domain name resolution configuration of the node, resulting in the inability to resolve domain names through kube-dns. The elasticsearch domain name resolution within the cluster fails. We need to modify the domain name resolution policy of the logagent to ClusterFirstWithHostNet.
Fixes #
```release-note
```
**Additional documentation e.g., KEPs …

fix(logagent): correct dns policy for logagent daemonset

---

.github/workflows/release.yml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): enable node test

---

test/e2e_installer/cluster/cluster_test.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): disable bootstrap app test

---

api/application/v1/defaults.go
pkg/application/registry/application/storage/rest.go
pkg/application/registry/application/storage/storage.go
pkg/application/registry/application/strategy.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fix(application): app status is Terminating, update will delete it

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

feat(ci): create mutil arch manifest in ci

---

pkg/monitor/controller/prometheus/yamls.go

1. idelta interval(2m) is not matched with prometheus scrape_interval(default is 1m), this will make the related series have break point frequently
2. (container_memory_usage_bytes - container_memory_cache) is not container's real memory use container_memory_working_set_bytes to replace it
> /kind bug
this pr fix bugs in prometheus record rules

fix(monitor): fix bug in prometheusrule

---

pkg/platform/provider/baremetal/phases/image/image.go

/kind feature
Change 'crictl' to 'nerdctl' will spped up pull process, since nerdctl will not using mirror config which will time out when mirror is not ready.
Fixes #
```release-note
```
```docs
```

feat(platform): change pull k8s images tool

---

pkg/platform/provider/baremetal/cluster/create.go
pkg/util/extenderapi/extenderapi.go

Clusternet v0.15.3 has changed naming rule for new helmrelease This patch provided a compatible way to get helmrelease name.
For existing helmrelease, use old nameing rule
For newly created helmrelease, use new namimg rule

fix(platform): adapt helmrelease new naming rule

---

pkg/controller/controller_utils.go
pkg/platform/controller/cluster/cluster_controller.go

> /kind bug
fix bug #2310
simple description:
cluster health check will failed in most case bacause the socket connection to the target cluster is not stable, so we check multiple times when for cluster health check.
Fixes #2310
```release-note
```
```docs
```

fix(health check): check cluster status for multiple times in health check go get rid of socket connection failure #2310

---

api/platform/types.go
api/platform/v1/types.go
pkg/platform/controller/cluster/cluster_controller.go

kind feature
1) add new cluster phase ClusterRecovering，which means the cluster is recovering form confined.
2) the transition of State Machine wil be:
(normal phase) -> Idling -> Confined -> Recovering -> (normal phase)
1) eks use Annotations to Distinguish those phase.
2)tke use db record to Distinguish those phase.
NONE
NONE

feat(platform):add new cluster phase ClusterRecovering
